CREATE TABLE IF NOT EXISTS county (
    `county_code` INT,
    `county_name` VARCHAR(15) CHARACTER SET utf8,
    `constituency_name` VARCHAR(19) CHARACTER SET utf8,
    `constituencies_wards` VARCHAR(25) CHARACTER SET utf8
);
INSERT INTO county VALUES (1,'Mombasa','Changamwe','Port Reitz'),
	(1,'Mombasa','Changamwe','Kipevu'),
	(1,'Mombasa','Changamwe','Airport'),
	(1,'Mombasa','Changamwe','Miritini'),
	(1,'Mombasa','Changamwe','Chaani'),
	(1,'Mombasa','Jomvu','Jomvu Kuu'),
	(1,'Mombasa','Jomvu','Magongo'),
	(1,'Mombasa','Jomvu','Mikindani'),
	(1,'Mombasa','Kisauni','Mjambere'),
	(1,'Mombasa','Kisauni','Junda'),
	(1,'Mombasa','Kisauni','Bamburi'),
	(1,'Mombasa','Kisauni','Mwakirunge'),
	(1,'Mombasa','Kisauni','Mtopanga'),
	(1,'Mombasa','Kisauni','Magogoni'),
	(1,'Mombasa','Kisauni','Shanzu'),
	(1,'Mombasa','Likoni','Mtongwe'),
	(1,'Mombasa','Likoni','Shika adabu'),
	(1,'Mombasa','Likoni','Bofu'),
	(1,'Mombasa','Likoni','Likoni'),
	(1,'Mombasa','Likoni','Timbwani'),
	(1,'Mombasa','Mvita','Mji wa Kale/Makadara'),
	(1,'Mombasa','Mvita','Tudor'),
	(1,'Mombasa','Mvita','Tononoka'),
	(1,'Mombasa','Mvita','Ganjoni/Shimanzi'),
	(1,'Mombasa','Mvita','Majengo'),
	(1,'Mombasa','Nyali','Frere Town'),
	(1,'Mombasa','Nyali','Ziwa la Ng''ombe'),
	(1,'Mombasa','Nyali','Mkomani'),
	(1,'Mombasa','Nyali','Kongowea'),
	(1,'Mombasa','Nyali','Ziwani/Kadzandani'),
	(2,'Kwale','Kinango','Ndavaya'),
	(2,'Kwale','Kinango','Puma'),
	(2,'Kwale','Kinango','Kinango'),
	(2,'Kwale','Kinango','Chengoni/Samburu'),
	(2,'Kwale','Kinango','Mackinon Road'),
	(2,'Kwale','Kinango','Mwavumbo'),
	(2,'Kwale','Kinango','Kasemeni'),
	(2,'Kwale','Lunga Lunga','Pongwe/Kikoneni'),
	(2,'Kwale','Lunga Lunga','Dzombo'),
	(2,'Kwale','Lunga Lunga','Vanga'),
	(2,'Kwale','Lunga Lunga',' Mwereni'),
	(2,'Kwale','Msambweni','Gombato Bongwe'),
	(2,'Kwale','Msambweni',' Ukunda'),
	(2,'Kwale','Msambweni','Kinondo'),
	(2,'Kwale','Msambweni','Ramisi'),
	(2,'Kwale','Matuga','  Tsimba Golini'),
	(2,'Kwale','Matuga','Waa'),
	(2,'Kwale','Matuga','Tiwi'),
	(2,'Kwale','Matuga','Kubo South'),
	(2,'Kwale','Matuga','Mkongani'),
	(3,'Kilifi','Matuga','Tezo'),
	(3,'Kilifi','Matuga','Sokoni'),
	(3,'Kilifi','Matuga','Kibarani'),
	(3,'Kilifi','Matuga','Dabaso'),
	(3,'Kilifi','Matuga','Matsangoni'),
	(3,'Kilifi','Matuga','Watamu'),
	(3,'Kilifi','Matuga','Mnarani'),
	(3,'Kilifi','Matuga','Junju'),
	(3,'Kilifi','Matuga','Mwarakaya'),
	(3,'Kilifi','Matuga','Shimo la Tewa'),
	(3,'Kilifi','Matuga','Chasimba'),
	(3,'Kilifi','Matuga','Mtepeni'),
	(3,'Kilifi','Matuga','Mariakani'),
	(3,'Kilifi','Matuga','Kayafungo'),
	(3,'Kilifi','Matuga','Kaloleni'),
	(3,'Kilifi','Matuga','Mwanamwinga'),
	(3,'Kilifi','Matuga','Dungicha'),
	(3,'Kilifi','Matuga','Bamba'),
	(3,'Kilifi','Matuga','Jaribuni'),
	(3,'Kilifi','Matuga','Sokoke'),
	(3,'Kilifi','Matuga','Maarafa'),
	(3,'Kilifi','Matuga','Magarini'),
	(3,'Kilifi','Matuga','Gongoni'),
	(3,'Kilifi','Matuga','Adu'),
	(3,'Kilifi','Matuga','Garashi'),
	(3,'Kilifi','Matuga','Sabaki'),
	(3,'Kilifi','Matuga','Mwawesa'),
	(3,'Kilifi','Matuga','Ruruma'),
	(3,'Kilifi','Matuga','Jibana'),
	(3,'Kilifi','Matuga','Rabai/Kisurutuni'),
	(3,'Kilifi','Matuga','Jilore'),
	(3,'Kilifi','Matuga','Kakuyuni'),
	(3,'Kilifi','Matuga','Ganda'),
	(3,'Kilifi','Matuga','Malindi Town'),
	(3,'Kilifi','Matuga','Shella'),
	(4,'Tana River','Garsen','Garsen Central'),
	(4,'Tana River','Garsen','Garsen East'),
	(4,'Tana River','Garsen','Garsen North'),
	(4,'Tana River','Garsen','Garsen South'),
	(4,'Tana River','Garsen','Kipini East'),
	(4,'Tana River','Garsen','Kipini West'),
	(4,'Tana River','Galole','Kinakomba'),
	(4,'Tana River','Galole','Mikinduni'),
	(4,'Tana River','Galole','Chewani'),
	(4,'Tana River','Galole','Wayu'),
	(4,'Tana River','Bura','Chewele'),
	(4,'Tana River','Bura','Hirimani'),
	(4,'Tana River','Bura','Bangale'),
	(4,'Tana River','Bura','Madogo'),
	(4,'Tana River','Bura','Sala'),
	(5,'Lamu','Lamu East','Faza'),
	(5,'Lamu','Lamu East','Kiunga'),
	(5,'Lamu','Lamu East','Basuba'),
	(5,'Lamu','Lamu West','Shella'),
	(5,'Lamu','Lamu West','Mkomani'),
	(5,'Lamu','Lamu West','Hindi'),
	(5,'Lamu','Lamu West','Mkunumbi'),
	(5,'Lamu','Lamu West','Hongwe'),
	(5,'Lamu','Lamu West','Witu'),
	(5,'Lamu','Lamu West','Bahari'),
	(6,'Taita-Taveta','Taveta','Chala'),
	(6,'Taita-Taveta','Taveta','Mahoo'),
	(6,'Taita-Taveta','Taveta','Bomani'),
	(6,'Taita-Taveta','Taveta','Mboghoni'),
	(6,'Taita-Taveta','Taveta','Mata'),
	(6,'Taita-Taveta','Wundanyi','Wundanyi/Mbale'),
	(6,'Taita-Taveta','Wundanyi','Werugha'),
	(6,'Taita-Taveta','Wundanyi','Wumingu/Kishushe'),
	(6,'Taita-Taveta','Wundanyi','Mwanda/Mgange'),
	(6,'Taita-Taveta','Mwatate','Ronge'),
	(6,'Taita-Taveta','Mwatate','Mwatate'),
	(6,'Taita-Taveta','Mwatate','Bura'),
	(6,'Taita-Taveta','Mwatate','Chawia'),
	(6,'Taita-Taveta','Mwatate','Wusi/Kishamba'),
	(6,'Taita-Taveta','Voi','Mbololo'),
	(6,'Taita-Taveta','Voi','Kaloleni'),
	(6,'Taita-Taveta','Voi','Sagala'),
	(6,'Taita-Taveta','Voi','Marungu'),
	(6,'Taita-Taveta','Voi','Kaigau'),
	(6,'Taita-Taveta','Voi','Ngolia'),
	(7,'Garissa','Dujis','Waberi'),
	(7,'Garissa','Dujis','Galbet'),
	(7,'Garissa','Dujis','Township'),
	(7,'Garissa','Dujis','Iftin'),
	(7,'Garissa','Balambala','Balambala'),
	(7,'Garissa','Balambala','Danyere'),
	(7,'Garissa','Balambala','Jarajara'),
	(7,'Garissa','Balambala','Saka'),
	(7,'Garissa','Balambala','Sankuri'),
	(7,'Garissa','Dadaab','Dertu'),
	(7,'Garissa','Dadaab','Dadaab'),
	(7,'Garissa','Dadaab','Labasigale'),
	(7,'Garissa','Dadaab','Damajale'),
	(7,'Garissa','Dadaab','Liboi'),
	(7,'Garissa','Dadaab','Abakaile'),
	(7,'Garissa','Fafi','Bura'),
	(7,'Garissa','Fafi','Dekaharia'),
	(7,'Garissa','Fafi','Jarajila'),
	(7,'Garissa','Fafi','Fafi'),
	(7,'Garissa','Fafi','Nanighi'),
	(7,'Garissa','Ijara','Hulugho'),
	(7,'Garissa','Ijara','Sangailu'),
	(7,'Garissa','Ijara','Ijara'),
	(7,'Garissa','Ijara','Masalani'),
	(7,'Garissa','Lagdera','Modogashe'),
	(7,'Garissa','Lagdera','Bename'),
	(7,'Garissa','Lagdera','Goreale'),
	(7,'Garissa','Lagdera','Maalamin'),
	(7,'Garissa','Lagdera','Sabena'),
	(7,'Garissa','Lagdera','Baraki'),
	(8,'Wajir','Wajir East','Wagbri'),
	(8,'Wajir','Wajir East','Township'),
	(8,'Wajir','Wajir East','Barwago'),
	(8,'Wajir','Wajir East','Khorof/Harar'),
	(8,'Wajir','Wajir North','Gurar'),
	(8,'Wajir','Wajir North','Bute'),
	(8,'Wajir','Wajir North','Korondile'),
	(8,'Wajir','Wajir North','Malkagufu'),
	(8,'Wajir','Wajir North','Batalu'),
	(8,'Wajir','Wajir North','Danaba'),
	(8,'Wajir','Wajir North','Godoma'),
	(8,'Wajir','Wajir South','Benane'),
	(8,'Wajir','Wajir South','Burder'),
	(8,'Wajir','Wajir South','Dadaja Bulla'),
	(8,'Wajir','Wajir South','Habaswein'),
	(8,'Wajir','Wajir South','Lagboghol South'),
	(8,'Wajir','Wajir South','Ibrahim Ure'),
	(8,'Wajir','Wajir West','Arbajahan'),
	(8,'Wajir','Wajir West','Hadado/Athibohol'),
	(8,'Wajir','Wajir West','Ademasajide'),
	(8,'Wajir','Wajir West','Ganyure'),
	(8,'Wajir','Wajir West','Wagalla'),
	(8,'Wajir','Tarbaj','Elben'),
	(8,'Wajir','Tarbaj','Sarman'),
	(8,'Wajir','Tarbaj','Tarbaj'),
	(8,'Wajir','Tarbaj','Wargadud'),
	(8,'Wajir','Eldas','Eldas'),
	(8,'Wajir','Eldas','Della'),
	(8,'Wajir','Eldas','Lakoley South/Basir'),
	(8,'Wajir','Eldas','Elnur/Tula Tula'),
	(9,'Mandera','Moyale','Butiye'),
	(9,'Mandera','Moyale','Sololo'),
	(9,'Mandera','Moyale','Heillu/Manyatta'),
	(9,'Mandera','Moyale','Golbo'),
	(9,'Mandera','Moyale','Moyale Township'),
	(9,'Mandera','Moyale','Uran'),
	(9,'Mandera','Moyale','Obbu'),
	(9,'Mandera','North Horr','Dukana'),
	(9,'Mandera','North Horr','Maikona'),
	(9,'Mandera','North Horr','Turbi'),
	(9,'Mandera','North Horr','North Horr'),
	(9,'Mandera','North Horr','Illeret'),
	(9,'Mandera','Laisamis','Loiyangalani'),
	(9,'Mandera','Laisamis','Kargi/South Horr'),
	(9,'Mandera','Laisamis','Korr/Ngurunit'),
	(9,'Mandera','Laisamis','Logo Logo'),
	(9,'Mandera','Laisamis','Laisamis'),
	(9,'Mandera','Saku','Sagate/Jaldesa'),
	(9,'Mandera','Saku','Karare'),
	(9,'Mandera','Saku','Marsabit Central'),
	(10,'Marsabit','Laisamis','  Loiyangalani'),
	(10,'Marsabit','Laisamis','Kargi/South Horr'),
	(10,'Marsabit','Laisamis','Korr/Ngurunit'),
	(10,'Marsabit','Laisamis','Logo Logo'),
	(10,'Marsabit','Laisamis','Laisamis'),
	(10,'Marsabit','North Horr','  Dukana'),
	(10,'Marsabit','North Horr','Maikona'),
	(10,'Marsabit','North Horr','Turbi'),
	(10,'Marsabit','North Horr','North Horr'),
	(10,'Marsabit','North Horr',' Illeret'),
	(10,'Marsabit','Saku','Sagate/Jaldesa'),
	(10,'Marsabit','Saku','Karare'),
	(10,'Marsabit','Saku','Marsabit Central'),
	(10,'Marsabit','Moyale','Butiye'),
	(10,'Marsabit','Moyale','Sololo'),
	(10,'Marsabit','Moyale','Heillu/Manyatta'),
	(10,'Marsabit','Moyale','Golbo'),
	(10,'Marsabit','Moyale','Moyale Township'),
	(10,'Marsabit','Moyale','Uran'),
	(10,'Marsabit','Moyale','Obbu'),
	(11,'Isiolo','Isiolo North','Wabera'),
	(11,'Isiolo','Isiolo North','Bulla Pesa'),
	(11,'Isiolo','Isiolo North','Chari'),
	(11,'Isiolo','Isiolo North','Cherab'),
	(11,'Isiolo','Isiolo North','Ngare Mara'),
	(11,'Isiolo','Isiolo North','Burat'),
	(11,'Isiolo','Isiolo North','Oldo/Nyiro'),
	(11,'Isiolo','Isiolo South','Garba Tulla'),
	(11,'Isiolo','Isiolo South','Kina'),
	(11,'Isiolo','Isiolo South','Sericho'),
	(12,'Meru','Buuri','Timau'),
	(12,'Meru','Buuri','Kisima'),
	(12,'Meru','Buuri','Kiirua/Naari'),
	(12,'Meru','Buuri','Ruiri/Rwarera'),
	(12,'Meru','Central Imenti','Mwanganthia'),
	(12,'Meru','Central Imenti','Abothuguchi Central'),
	(12,'Meru','Central Imenti','Abothuguchi West'),
	(12,'Meru','Central Imenti','Kiagu'),
	(12,'Meru','Central Imenti','Kibirichia'),
	(12,'Meru','Igembe Central','Akirang''ondu');
INSERT INTO county VALUES (12,'Meru','Igembe Central','Athiru'),
	(12,'Meru','Igembe Central','Ruujine'),
	(12,'Meru','Igembe Central','Igembe East Njia'),
	(12,'Meru','Igembe Central','Kangeta'),
	(12,'Meru','Igembe South','Maua'),
	(12,'Meru','Igembe South','Kegoi/Antubochiu'),
	(12,'Meru','Igembe South','Athiru'),
	(12,'Meru','Igembe South','Gaiti'),
	(12,'Meru','Igembe South','Akachiu'),
	(12,'Meru','Igembe South','Kanuni'),
	(12,'Meru','Igembe North','Antuambui'),
	(12,'Meru','Igembe North','Ntunene'),
	(12,'Meru','Igembe North','Antubetwe Kiongo'),
	(12,'Meru','Igembe North','Naathui'),
	(12,'Meru','Igembe North','Amwathi'),
	(12,'Meru','Tigania West','Athwana'),
	(12,'Meru','Tigania West','Akithi'),
	(12,'Meru','Tigania West','Kianjai'),
	(12,'Meru','Tigania West','Nkomo'),
	(12,'Meru','Tigania West','Mbeu'),
	(12,'Meru','Tigania East','Thangatha'),
	(12,'Meru','Tigania East','Mikinduri'),
	(12,'Meru','Tigania East','Kiguchwa'),
	(12,'Meru','Tigania East','Mithara'),
	(12,'Meru','Tigania East','Karama'),
	(12,'Meru','Imenti North','Municipality'),
	(12,'Meru','Imenti North','Ntima East'),
	(12,'Meru','Imenti North','Ntima West'),
	(12,'Meru','Imenti North','Nyaki West'),
	(12,'Meru','Imenti North','Nyaki East'),
	(12,'Meru','Imenti South','Mitunguu'),
	(12,'Meru','Imenti South','Igoji East'),
	(12,'Meru','Imenti South','Igoji West'),
	(12,'Meru','Imenti South','Abogeta East'),
	(12,'Meru','Imenti South','Abogeta West'),
	(12,'Meru','Imenti South','Nkuene'),
	(13,'Tharaka Nithi','Tharaka ','Gatunga'),
	(13,'Tharaka Nithi','Tharaka ','Mukothima'),
	(13,'Tharaka Nithi','Tharaka ','Nkondi'),
	(13,'Tharaka Nithi','Tharaka ','Chiakariga'),
	(13,'Tharaka Nithi','Tharaka ','Marimanti'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Mariani'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Karingani'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Magumoni'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Mugwe'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Igambang''ombe'),
	(13,'Tharaka Nithi','Maara','Mitheru'),
	(13,'Tharaka Nithi','Maara','Muthambi'),
	(13,'Tharaka Nithi','Maara','Mwimbi'),
	(13,'Tharaka Nithi','Maara','Ganga'),
	(13,'Tharaka Nithi','Maara','Chogoria'),
	(14,'Embu','Manyatta','Ruguru/Ngandori'),
	(14,'Embu','Manyatta','Kithimu'),
	(14,'Embu','Manyatta','Nginda'),
	(14,'Embu','Manyatta','Mbeti North'),
	(14,'Embu','Manyatta','Kirimari'),
	(14,'Embu','Manyatta','Gaturi South'),
	(14,'Embu','Runyenjes','Gaturi North'),
	(14,'Embu','Runyenjes','Kagaari South'),
	(14,'Embu','Runyenjes','Kagaari North'),
	(14,'Embu','Runyenjes','Central Ward'),
	(14,'Embu','Runyenjes','Kyeni North'),
	(14,'Embu','Runyenjes','Kyeni South'),
	(14,'Embu','Mbeere North','Nthawa'),
	(14,'Embu','Mbeere North','Muminji'),
	(14,'Embu','Mbeere North','Evurore'),
	(14,'Embu','Mbeere South','Mwea'),
	(14,'Embu','Mbeere South','Amakim'),
	(14,'Embu','Mbeere South','Mbeti South'),
	(14,'Embu','Mbeere South','Mavuria'),
	(14,'Embu','Mbeere South','Kiambere'),
	(15,'Kitui','Kitui West','Mutonguni'),
	(15,'Kitui','Kitui West','Kauwi'),
	(15,'Kitui','Kitui West','Matinyani'),
	(15,'Kitui','Kitui West','Kwa Mutonga/Kithum Ula'),
	(15,'Kitui','Kitui Central','Miambani'),
	(15,'Kitui','Kitui Central','Township Kyangwithya West'),
	(15,'Kitui','Kitui Central','Mulango'),
	(15,'Kitui','Kitui Central','Kyangwithya East'),
	(15,'Kitui','Kitui Rural','Kisasi'),
	(15,'Kitui','Kitui Rural','Mbitini'),
	(15,'Kitui','Kitui Rural','Kwavonza/Yatta'),
	(15,'Kitui','Kitui Rural','Kanyangi'),
	(15,'Kitui','Kitui South','Ikana/Kyantune'),
	(15,'Kitui','Kitui South','Mutomo'),
	(15,'Kitui','Kitui South','Mutha'),
	(15,'Kitui','Kitui South','Ikutha'),
	(15,'Kitui','Kitui South','Kanziko'),
	(15,'Kitui','Kitui South','Athi'),
	(15,'Kitui','Kitui East','Zombe/Mwitika'),
	(15,'Kitui','Kitui East','Nzambani'),
	(15,'Kitui','Kitui East','Chuluni'),
	(15,'Kitui','Kitui East','Voo/Kyamatu'),
	(15,'Kitui','Kitui East','Endau/Malalani'),
	(15,'Kitui','Kitui East','Mutito/Kaliku'),
	(15,'Kitui','Mwingi North','Ngomeni'),
	(15,'Kitui','Mwingi North','Kyuso'),
	(15,'Kitui','Mwingi North','Mumoni'),
	(15,'Kitui','Mwingi North','Tseikuru'),
	(15,'Kitui','Mwingi North','Tharaka'),
	(15,'Kitui','Mwingi West','Kyome/Thaana'),
	(15,'Kitui','Mwingi West','Nguutani'),
	(15,'Kitui','Mwingi West','Migwani'),
	(15,'Kitui','Mwingi West','Kiomo/Kyethani'),
	(15,'Kitui','Mwingi Central','Central'),
	(15,'Kitui','Mwingi Central','Kivou'),
	(15,'Kitui','Mwingi Central','Nguni'),
	(15,'Kitui','Mwingi Central','Mui'),
	(15,'Kitui','Mwingi Central','Waita'),
	(16,'Machakos','Mwingi Central','Masinga','Kivaa'),
	(16,'Machakos','Mwingi Central','Masinga','Masinga'),
	(16,'Machakos','Mwingi Central','Masinga','Central'),
	(16,'Machakos','Mwingi Central','Masinga','Ekalakala'),
	(16,'Machakos','Mwingi Central','Masinga','Muthesya'),
	(16,'Machakos','Mwingi Central','Masinga','Ndithini'),
	(16,'Machakos','Mwingi Central','Yatta','Ndalani'),
	(16,'Machakos','Mwingi Central','Yatta','Matuu'),
	(16,'Machakos','Mwingi Central','Yatta','Kithimani'),
	(16,'Machakos','Mwingi Central','Yatta','Ikomba'),
	(16,'Machakos','Mwingi Central','Yatta','Katangi'),
	(16,'Machakos','Mwingi Central','Matungulu','Tala'),
	(16,'Machakos','Mwingi Central','Matungulu','Matungulu North'),
	(16,'Machakos','Mwingi Central','Matungulu','Matungulu East'),
	(16,'Machakos','Mwingi Central','Matungulu','Matungulu West'),
	(16,'Machakos','Mwingi Central','Matungulu','Kyeleni'),
	(16,'Machakos','Mwingi Central','Kangundo','Kangundo North'),
	(16,'Machakos','Mwingi Central','Kangundo','Kangundo Central'),
	(16,'Machakos','Mwingi Central','Kangundo','Kangundo East'),
	(16,'Machakos','Mwingi Central','Kangundo','Kangundo West'),
	(16,'Machakos','Mwingi Central','Mwala','Mbiuni'),
	(16,'Machakos','Mwingi Central','Mwala','Makutano/Mwala'),
	(16,'Machakos','Mwingi Central','Mwala','Masii'),
	(16,'Machakos','Mwingi Central','Mwala','Muthetheni'),
	(16,'Machakos','Mwingi Central','Mwala','Wamunyu'),
	(16,'Machakos','Mwingi Central','Mwala','Kibauni'),
	(16,'Machakos','Mwingi Central','Kathiani','Mitaboni'),
	(16,'Machakos','Mwingi Central','Kathiani','Kathiani Central'),
	(16,'Machakos','Mwingi Central','Kathiani','Upper Kaewa/Iveti'),
	(16,'Machakos','Mwingi Central','Kathiani','Lower Kaewa/Kaani'),
	(16,'Machakos','Mwingi Central','Machakos Town','Kalama'),
	(16,'Machakos','Mwingi Central','Machakos Town','Mua'),
	(16,'Machakos','Mwingi Central','Machakos Town','Mutitini'),
	(16,'Machakos','Mwingi Central','Machakos Town','Machakos Central'),
	(16,'Machakos','Mwingi Central','Machakos Town','Mumbuni North'),
	(16,'Machakos','Mwingi Central','Machakos Town','Muvuti/Kiima-Kimwe'),
	(16,'Machakos','Mwingi Central','Machakos Town','Kola'),
	(16,'Machakos','Mwingi Central','Mavoko','Athi River'),
	(16,'Machakos','Mwingi Central','Mavoko','Kinanie'),
	(16,'Machakos','Mwingi Central','Mavoko','Muthwani'),
	(16,'Machakos','Mwingi Central','Mavoko','Syokimau/Mulolongo'),
	(17,'Makueni','Mwingi Central','Mbooni','Tulimani'),
	(17,'Makueni','Mwingi Central','Mbooni','Mbooni'),
	(17,'Makueni','Mwingi Central','Mbooni','Kithungo/Kitundu'),
	(17,'Makueni','Mwingi Central','Mbooni','Kiteta/Kisau'),
	(17,'Makueni','Mwingi Central','Mbooni','Waia-Kako'),
	(17,'Makueni','Mwingi Central','Mbooni','Kalawa'),
	(17,'Makueni','Mwingi Central','Kaiti','Ukia'),
	(17,'Makueni','Mwingi Central','Kaiti','Kee'),
	(17,'Makueni','Mwingi Central','Kaiti','Kilungu'),
	(17,'Makueni','Mwingi Central','Kaiti','Ilima'),
	(17,'Makueni','Mwingi Central','Makueni','Wote'),
	(17,'Makueni','Mwingi Central','Makueni','Muvau/Kikuumini'),
	(17,'Makueni','Mwingi Central','Makueni','Mavindini'),
	(17,'Makueni','Mwingi Central','Makueni','Kitise/Kithuki'),
	(17,'Makueni','Mwingi Central','Makueni','Kathonzweni'),
	(17,'Makueni','Mwingi Central','Makueni','Nzau/Kilili/Kalamba'),
	(17,'Makueni','Mwingi Central','Makueni','Mbitini'),
	(17,'Makueni','Mwingi Central','Kilome','Kasikeu'),
	(17,'Makueni','Mwingi Central','Kilome','Mukaa'),
	(17,'Makueni','Mwingi Central','Kilome','Kiima Kiu/Kalanzoni'),
	(17,'Makueni','Mwingi Central','Kibwezi East','Masongaleni'),
	(17,'Makueni','Mwingi Central','Kibwezi East','Mtito Andei'),
	(17,'Makueni','Mwingi Central','Kibwezi East','Thange'),
	(17,'Makueni','Mwingi Central','Kibwezi East','Ivingoni/Nzambani'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Makindu'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Nguumo'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Kikumbulyu North'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Kimumbulyu South'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Nguu/Masumba'),
	(17,'Makueni','Mwingi Central','Kibwezi West','Emali/Mulala'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Engineer'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Gathara'),
	(18,'Nyandarua','Mwingi Central','Kinangop','North Kinangop'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Murungaru'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Njabini/Kiburu'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Nyakio'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Githabai'),
	(18,'Nyandarua','Mwingi Central','Kinangop','Magumu'),
	(18,'Nyandarua','Mwingi Central','Kipipiri','Wanjohi'),
	(18,'Nyandarua','Mwingi Central','Kipipiri','Kipipiri'),
	(18,'Nyandarua','Mwingi Central','Kipipiri','Geta'),
	(18,'Nyandarua','Mwingi Central','Kipipiri','Githioro'),
	(18,'Nyandarua','Mwingi Central','Ol Joro Orok','Gathanji'),
	(18,'Nyandarua','Mwingi Central','Ol Joro Orok','Gatima'),
	(18,'Nyandarua','Mwingi Central','Ol Joro Orok','Weru'),
	(18,'Nyandarua','Mwingi Central','Ol Joro Orok','Charagita'),
	(18,'Nyandarua','Mwingi Central','Ndaragwa','Leshau/Pondo'),
	(18,'Nyandarua','Mwingi Central','Ndaragwa','Kiriita'),
	(18,'Nyandarua','Mwingi Central','Ndaragwa','Central'),
	(18,'Nyandarua','Mwingi Central','Ndaragwa','Shamata'),
	(18,'Nyandarua','Mwingi Central','Ol Kalou','Karau'),
	(18,'Nyandarua','Mwingi Central','Ol Kalou','Kanjuiri Range'),
	(18,'Nyandarua','Mwingi Central','Ol Kalou','Mirangine'),
	(18,'Nyandarua','Mwingi Central','Ol Kalou','Kaimbaga'),
	(18,'Nyandarua','Mwingi Central','Ol Kalou','Rurii'),
	(19,'Nyeri','Mwingi Central','Mathira','Ruguru'),
	(19,'Nyeri','Mwingi Central','Mathira','Magutu'),
	(19,'Nyeri','Mwingi Central','Mathira','Iriani'),
	(19,'Nyeri','Mwingi Central','Mathira','Konyu'),
	(19,'Nyeri','Mwingi Central','Mathira','Kirimukuyu'),
	(19,'Nyeri','Mwingi Central','Mathira','Karatina Town'),
	(19,'Nyeri','Mwingi Central','Othaya','Mahiga'),
	(19,'Nyeri','Mwingi Central','Othaya','Iria-Ini'),
	(19,'Nyeri','Mwingi Central','Othaya','Chinga'),
	(19,'Nyeri','Mwingi Central','Othaya','Karima'),
	(19,'Nyeri','Mwingi Central','Tetu','Dedan Kimathi'),
	(19,'Nyeri','Mwingi Central','Tetu','Wamagana'),
	(19,'Nyeri','Mwingi Central','Tetu','Aguthi-Gaaki'),
	(19,'Nyeri','Mwingi Central','Mukurweini','Gikondi'),
	(19,'Nyeri','Mwingi Central','Mukurweini','Rugi'),
	(19,'Nyeri','Mwingi Central','Mukurweini','Mukurwe-Ini West'),
	(19,'Nyeri','Mwingi Central','Mukurweini','Mukurwe-Ini Central'),
	(19,'Nyeri','Mwingi Central','Tetu','Dedan Kimathi'),
	(19,'Nyeri','Mwingi Central','Tetu','Wamagana'),
	(19,'Nyeri','Mwingi Central','Tetu','Aguthi-Gaaki'),
	(19,'Nyeri','Mwingi Central','Nyeri Town','Kiganjo/Mathari'),
	(19,'Nyeri','Mwingi Central','Nyeri Town','Rware'),
	(19,'Nyeri','Mwingi Central','Nyeri Town','Gatitu/Muruguru'),
	(19,'Nyeri','Mwingi Central','Nyeri Town','Ruring’u'),
	(19,'Nyeri','Mwingi Central','Nyeri Town','Kamakwa/Mukaro'),
	(19,'Nyeri','Mwingi Central','Kieni','Mweiga'),
	(19,'Nyeri','Mwingi Central','Kieni','Naromoro Kiamthaga'),
	(19,'Nyeri','Mwingi Central','Kieni','Mwiyogo/Endara Sha'),
	(19,'Nyeri','Mwingi Central','Kieni','Mugunda'),
	(19,'Nyeri','Mwingi Central','Kieni','Gatarakwa'),
	(19,'Nyeri','Mwingi Central','Kieni','Thegu River'),
	(19,'Nyeri','Mwingi Central','Kieni','Kabaru'),
	(19,'Nyeri','Mwingi Central','Kieni','Gakawa'),
	(20,'Kirinyaga','Mwingi Central','Kirinyaga Central','Mutira'),
	(20,'Kirinyaga','Mwingi Central','Kirinyaga Central','Kanyekini'),
	(20,'Kirinyaga','Mwingi Central','Kirinyaga Central','Kerugoya'),
	(20,'Kirinyaga','Mwingi Central','Kirinyaga Central','Inoi'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Mutithi'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Kangai'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Wamumu'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Nyangati'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Murindiko'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Gathigiriri'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Teberer'),
	(20,'Kirinyaga','Mwingi Central','Mwea','Thiba');
INSERT INTO county VALUES (20,'Kirinyaga','Mwingi Central','Gichugu','Kabare Baragwi'),
	(20,'Kirinyaga','Mwingi Central','Gichugu','Njukiini'),
	(20,'Kirinyaga','Mwingi Central','Gichugu','Ngariama'),
	(20,'Kirinyaga','Mwingi Central','Gichugu','Karumandi'),
	(20,'Kirinyaga','Mwingi Central','Ndia','Mukure'),
	(20,'Kirinyaga','Mwingi Central','Ndia','Kiine'),
	(20,'Kirinyaga','Mwingi Central','Ndia','Kariti'),
	(21,'Murang''a','Mwingi Central','Gatanga','Ithanga'),
	(21,'Murang''a','Mwingi Central','Gatanga','Kakuzi/Mitubiri'),
	(21,'Murang''a','Mwingi Central','Gatanga','Mugumo-Ini'),
	(21,'Murang''a','Mwingi Central','Gatanga','Kihumbu-Ini'),
	(21,'Murang''a','Mwingi Central','Gatanga','Gatanga'),
	(21,'Murang''a','Mwingi Central','Gatanga','Kariara'),
	(21,'Murang''a','Mwingi Central','Kandara','Ng’ararii'),
	(21,'Murang''a','Mwingi Central','Kandara','Muruka'),
	(21,'Murang''a','Mwingi Central','Kandara','Kangundu-Ini'),
	(21,'Murang''a','Mwingi Central','Kandara','Gaichanjiru'),
	(21,'Murang''a','Mwingi Central','Kandara','Ithiru'),
	(21,'Murang''a','Mwingi Central','Kandara','Ruchu'),
	(21,'Murang''a','Mwingi Central','Kigumo','Kahumbu'),
	(21,'Murang''a','Mwingi Central','Kigumo','Muthithi'),
	(21,'Murang''a','Mwingi Central','Kigumo','Kigumo'),
	(21,'Murang''a','Mwingi Central','Kigumo','Kangari'),
	(21,'Murang''a','Mwingi Central','Kigumo','Kinyona'),
	(21,'Murang''a','Mwingi Central','Mathioya','Gituhi'),
	(21,'Murang''a','Mwingi Central','Mathioya','Kiru'),
	(21,'Murang''a','Mwingi Central','Mathioya','Kamacharia'),
	(21,'Murang''a','Mwingi Central','Kiharu','Wangu'),
	(21,'Murang''a','Mwingi Central','Kiharu','Mugoiri'),
	(21,'Murang''a','Mwingi Central','Kiharu','Mbiri'),
	(21,'Murang''a','Mwingi Central','Kiharu','Township'),
	(21,'Murang''a','Mwingi Central','Kiharu','Murarandia'),
	(21,'Murang''a','Mwingi Central','Kiharu','Gaturi'),
	(21,'Murang''a','Mwingi Central','Kangema','Kanyenya-Ini'),
	(21,'Murang''a','Mwingi Central','Kangema','Muguru'),
	(21,'Murang''a','Mwingi Central','Kangema','Rwathia'),
	(21,'Murang''a','Mwingi Central','Maragwa','Kimorori/Wempa'),
	(21,'Murang''a','Mwingi Central','Maragwa','Makuyu'),
	(21,'Murang''a','Mwingi Central','Maragwa','Kambiti'),
	(21,'Murang''a','Mwingi Central','Maragwa','Kamahuha'),
	(21,'Murang''a','Mwingi Central','Maragwa','Ichagaki'),
	(21,'Murang''a','Mwingi Central','Maragwa','Nginda'),
	(22,'Kiambu','Mwingi Central','Gatundu North','Gituamba'),
	(22,'Kiambu','Mwingi Central','Gatundu North','Githobokoni'),
	(22,'Kiambu','Mwingi Central','Gatundu North','Chania'),
	(22,'Kiambu','Mwingi Central','Gatundu North','Mang’u'),
	(22,'Kiambu','Mwingi Central','Gatundu South','Kiamwangi'),
	(22,'Kiambu','Mwingi Central','Gatundu South','Kiganjo'),
	(22,'Kiambu','Mwingi Central','Gatundu South','Ndarugu'),
	(22,'Kiambu','Mwingi Central','Gatundu South','Ngenda'),
	(22,'Kiambu','Mwingi Central','Githunguri','Githunguri'),
	(22,'Kiambu','Mwingi Central','Githunguri','Githiga'),
	(22,'Kiambu','Mwingi Central','Githunguri','Ikinu'),
	(22,'Kiambu','Mwingi Central','Githunguri','Ngewa'),
	(22,'Kiambu','Mwingi Central','Githunguri','Komothai'),
	(22,'Kiambu','Mwingi Central','Juja','Murera'),
	(22,'Kiambu','Mwingi Central','Juja','Theta'),
	(22,'Kiambu','Mwingi Central','Juja','Juja'),
	(22,'Kiambu','Mwingi Central','Juja','Witeithie'),
	(22,'Kiambu','Mwingi Central','Juja','Kalimoni'),
	(22,'Kiambu','Mwingi Central','Kabete','Gitaru'),
	(22,'Kiambu','Mwingi Central','Kabete','Muguga'),
	(22,'Kiambu','Mwingi Central','Kabete','Nyathuna'),
	(22,'Kiambu','Mwingi Central','Kabete','Kabete'),
	(22,'Kiambu','Mwingi Central','Kabete','Uthiru'),
	(22,'Kiambu','Mwingi Central','Kiambaa','Cianda'),
	(22,'Kiambu','Mwingi Central','Kiambaa','Karuiri'),
	(22,'Kiambu','Mwingi Central','Kiambaa','Ndenderu'),
	(22,'Kiambu','Mwingi Central','Kiambaa','Muchatha'),
	(22,'Kiambu','Mwingi Central','Kiambaa','Kihara'),
	(22,'Kiambu','Mwingi Central','Kiambu','Ting’gang’a'),
	(22,'Kiambu','Mwingi Central','Kiambu','Ndumberi'),
	(22,'Kiambu','Mwingi Central','Kiambu','Riabai'),
	(22,'Kiambu','Mwingi Central','Kiambu','Township'),
	(22,'Kiambu','Mwingi Central','Limuru','Bibirioni'),
	(22,'Kiambu','Mwingi Central','Limuru','Limuru Central'),
	(22,'Kiambu','Mwingi Central','Limuru','Ndeiya'),
	(22,'Kiambu','Mwingi Central','Limuru','Limuru East'),
	(22,'Kiambu','Mwingi Central','Limuru','Ngecha Tigoni'),
	(22,'Kiambu','Mwingi Central','Kikuyu','Karai'),
	(22,'Kiambu','Mwingi Central','Kikuyu','Nachu'),
	(22,'Kiambu','Mwingi Central','Kikuyu','Sigona'),
	(22,'Kiambu','Mwingi Central','Kikuyu','Kikuyu'),
	(22,'Kiambu','Mwingi Central','Kikuyu','Kinoo'),
	(22,'Kiambu','Mwingi Central','Lari','Kijabe'),
	(22,'Kiambu','Mwingi Central','Lari','Nyanduma'),
	(22,'Kiambu','Mwingi Central','Lari','Kamburu'),
	(22,'Kiambu','Mwingi Central','Lari','Lari/Kirenga'),
	(22,'Kiambu','Mwingi Central','Ruiru','Gitothua'),
	(22,'Kiambu','Mwingi Central','Ruiru','Biashara'),
	(22,'Kiambu','Mwingi Central','Ruiru','Gatongora'),
	(22,'Kiambu','Mwingi Central','Ruiru','Kahawa Sukari'),
	(22,'Kiambu','Mwingi Central','Ruiru','Kahawa Wendani'),
	(22,'Kiambu','Mwingi Central','Ruiru','Kiuu'),
	(22,'Kiambu','Mwingi Central','Ruiru','Mwiki'),
	(22,'Kiambu','Mwingi Central','Ruiru','Mwihoko'),
	(22,'Kiambu','Mwingi Central','Thika Town','Township'),
	(22,'Kiambu','Mwingi Central','Thika Town','Kamenu'),
	(22,'Kiambu','Mwingi Central','Thika Town','Hospital'),
	(22,'Kiambu','Mwingi Central','Thika Town','Gatuanyaga'),
	(22,'Kiambu','Mwingi Central','Thika Town','Ngoliba'),
	(23,'Turkana','Mwingi Central','Turkana Central','Kerio Delta'),
	(23,'Turkana','Mwingi Central','Turkana Central','Kang’atotha'),
	(23,'Turkana','Mwingi Central','Turkana Central','Kalokol'),
	(23,'Turkana','Mwingi Central','Turkana Central','Lodwar Township'),
	(23,'Turkana','Mwingi Central','Turkana Central','Kanamkemer'),
	(23,'Turkana','Mwingi Central','Turkana East','Kapedo/Napeito'),
	(23,'Turkana','Mwingi Central','Turkana East','Katilia'),
	(23,'Turkana','Mwingi Central','Turkana East','Lokori/Kochodin'),
	(23,'Turkana','Mwingi Central','Turkana North','Kaeris'),
	(23,'Turkana','Mwingi Central','Turkana North','Lake zone'),
	(23,'Turkana','Mwingi Central','Turkana North','Lapur'),
	(23,'Turkana','Mwingi Central','Turkana North','Kaaleng/kaikor'),
	(23,'Turkana','Mwingi Central','Turkana North','Kibish'),
	(23,'Turkana','Mwingi Central','Turkana North','Nakalale'),
	(23,'Turkana','Mwingi Central','Turkana South','Kaputir'),
	(23,'Turkana','Mwingi Central','Turkana South','Katilu'),
	(23,'Turkana','Mwingi Central','Turkana South','Lobokat'),
	(23,'Turkana','Mwingi Central','Turkana South','Kalapata'),
	(23,'Turkana','Mwingi Central','Turkana South','Lokichar'),
	(23,'Turkana','Mwingi Central','Turkana West','Kakuma'),
	(23,'Turkana','Mwingi Central','Turkana West','Lopur'),
	(23,'Turkana','Mwingi Central','Turkana West','Letea'),
	(23,'Turkana','Mwingi Central','Turkana West','Songot'),
	(23,'Turkana','Mwingi Central','Turkana West','Kalobeyei'),
	(23,'Turkana','Mwingi Central','Turkana West','Lokichoggio'),
	(23,'Turkana','Mwingi Central','Turkana West','Nanaam'),
	(23,'Turkana','Mwingi Central','Loima','Kotaruk/Lobei'),
	(23,'Turkana','Mwingi Central','Loima','Turkwel'),
	(23,'Turkana','Mwingi Central','Loima','Loima'),
	(23,'Turkana','Mwingi Central','Loima','Lokiriama/Loren Gippi'),
	(24,'West pokot','Mwingi Central','Kapenguria','Riwo'),
	(24,'West pokot','Mwingi Central','Kapenguria','Kapenguria'),
	(24,'West pokot','Mwingi Central','Kapenguria','Mnagei'),
	(24,'West pokot','Mwingi Central','Kapenguria','Siyoi'),
	(24,'West pokot','Mwingi Central','Kapenguria','Endugh'),
	(24,'West pokot','Mwingi Central','Kapenguria','Sook'),
	(24,'West pokot','Mwingi Central','Sigor','Sekerr'),
	(24,'West pokot','Mwingi Central','Sigor','Masool'),
	(24,'West pokot','Mwingi Central','Sigor','Lomut'),
	(24,'West pokot','Mwingi Central','Sigor','Weiwei'),
	(24,'West pokot','Mwingi Central','Kacheliba','Suam'),
	(24,'West pokot','Mwingi Central','Kacheliba','Kodich'),
	(24,'West pokot','Mwingi Central','Kacheliba','Kasei'),
	(24,'West pokot','Mwingi Central','Kacheliba','Kapchok'),
	(24,'West pokot','Mwingi Central','Kacheliba','Kiwawa'),
	(24,'West pokot','Mwingi Central','Kacheliba','Alale'),
	(24,'West pokot','Mwingi Central','Pokot South','Chepareria'),
	(24,'West pokot','Mwingi Central','Pokot South','Batei'),
	(24,'West pokot','Mwingi Central','Pokot South','Lelan'),
	(24,'West pokot','Mwingi Central','Pokot South','Tapach'),
	(25,'Samburu','Mwingi Central','Samburu East','Waso'),
	(25,'Samburu','Mwingi Central','Samburu East','Wamba West'),
	(25,'Samburu','Mwingi Central','Samburu East','Wamba East'),
	(25,'Samburu','Mwingi Central','Samburu East','Wamba North'),
	(25,'Samburu','Mwingi Central','Samburu North','El-Barta'),
	(25,'Samburu','Mwingi Central','Samburu North','Nachola'),
	(25,'Samburu','Mwingi Central','Samburu North','Ndoto'),
	(25,'Samburu','Mwingi Central','Samburu North','Nyiro'),
	(25,'Samburu','Mwingi Central','Samburu North','Angata Nanyokie'),
	(25,'Samburu','Mwingi Central','Samburu North','Baawa'),
	(25,'Samburu','Mwingi Central','Samburu West','Lodokejek'),
	(25,'Samburu','Mwingi Central','Samburu West','Suguta Marmar'),
	(25,'Samburu','Mwingi Central','Samburu West','Maralal'),
	(25,'Samburu','Mwingi Central','Samburu West','Loosuk'),
	(25,'Samburu','Mwingi Central','Samburu West','Poro'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Sinyerere'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Makutano'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Kaplamai'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Motosiet'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Cherangany/Suwerwa'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Chepsiro/Kiptoror'),
	(26,'Trans-Nzoia','Mwingi Central','Cherang''any','Sitatunga'),
	(26,'Trans-Nzoia','Mwingi Central','Kwanza','Kapomboi'),
	(26,'Trans-Nzoia','Mwingi Central','Kwanza','Kwanza'),
	(26,'Trans-Nzoia','Mwingi Central','Kwanza','Keiyo'),
	(26,'Trans-Nzoia','Mwingi Central','Kwanza','Bidii'),
	(26,'Trans-Nzoia','Mwingi Central','Endebess','Chepchoina'),
	(26,'Trans-Nzoia','Mwingi Central','Endebess','Endebess'),
	(26,'Trans-Nzoia','Mwingi Central','Endebess','Matumbei'),
	(26,'Trans-Nzoia','Mwingi Central','Saboti','Kinyoro'),
	(26,'Trans-Nzoia','Mwingi Central','Saboti','Matisi'),
	(26,'Trans-Nzoia','Mwingi Central','Saboti','Tuwani'),
	(26,'Trans-Nzoia','Mwingi Central','Saboti','Saboti'),
	(26,'Trans-Nzoia','Mwingi Central','Saboti','Machewa'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Kiminini'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Waitaluk'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Sirende'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Hospital'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Sikhendu'),
	(26,'Trans-Nzoia','Mwingi Central','Kiminini','Nabiswa'),
	(27,'Uasin Gishu','Mwingi Central','Ainabkoi','Kapsoya'),
	(27,'Uasin Gishu','Mwingi Central','Ainabkoi','Kaptagat'),
	(27,'Uasin Gishu','Mwingi Central','Ainabkoi','Ainabkoi/Olare'),
	(27,'Uasin Gishu','Mwingi Central','Kapseret','Simat/Kapseret'),
	(27,'Uasin Gishu','Mwingi Central','Kapseret','Kipkenyo'),
	(27,'Uasin Gishu','Mwingi Central','Kapseret','Ngeria'),
	(27,'Uasin Gishu','Mwingi Central','Kapseret','Megun'),
	(27,'Uasin Gishu','Mwingi Central','Kapseret','Langas'),
	(27,'Uasin Gishu','Mwingi Central','Kesses','Racecourse'),
	(27,'Uasin Gishu','Mwingi Central','Kesses','Cheptiret/Kipchamo'),
	(27,'Uasin Gishu','Mwingi Central','Kesses','Tulwet/Chuiyat'),
	(27,'Uasin Gishu','Mwingi Central','Kesses','Tarakwa'),
	(27,'Uasin Gishu','Mwingi Central','Moiben','Tembelio'),
	(27,'Uasin Gishu','Mwingi Central','Moiben','Sergoit'),
	(27,'Uasin Gishu','Mwingi Central','Moiben','Karuna/Meibeki'),
	(27,'Uasin Gishu','Mwingi Central','Moiben','Moiben'),
	(27,'Uasin Gishu','Mwingi Central','Moiben','Kimumu'),
	(27,'Uasin Gishu','Mwingi Central','Soy','  Moi’s Bridge'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Kapkures'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Ziwa'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Segero/Barsombe'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Kipsom Ba'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Soy'),
	(27,'Uasin Gishu','Mwingi Central','Soy','Kuinet/Kapsuswa'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','  Ngenyilel'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','Tapsagoi'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','Kamagut'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','Kiplombe'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','Kapsaos'),
	(27,'Uasin Gishu','Mwingi Central','Turbo','Huruma'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo North','Emsoo'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo North','Kamariny'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo North','Kapchemutwa'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo North','Tambach'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Kaptarakwa'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Chepkorio'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Soy North'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Soy South'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Kabiemit'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Keiyo South','Metkei'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet East','Kapyego'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet East','Sambirir'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet East','Endo'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet East','Embobut / Embulot'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Kapsowar'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Lelan'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Sengwer'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Cherang’any/Chebororwa'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Moiben/Kuserwo'),
	(28,'Elgeyo-Marakwet','Mwingi Central','Marakwet West','Arror'),
	(29,'Nandi','Mwingi Central','Aldai','Kabwareng'),
	(29,'Nandi','Mwingi Central','Aldai','Terik'),
	(29,'Nandi','Mwingi Central','Aldai','Kemeloi-Maraba'),
	(29,'Nandi','Mwingi Central','Aldai','Kobujoi'),
	(29,'Nandi','Mwingi Central','Aldai','Kaptumo-Kaboi'),
	(29,'Nandi','Mwingi Central','Aldai','Koyo-Ndurio'),
	(29,'Nandi','Mwingi Central','Chesumei','Chemundu/Kapng’etuny'),
	(29,'Nandi','Mwingi Central','Chesumei','Kosirai'),
	(29,'Nandi','Mwingi Central','Chesumei','Lelmokwo/Ngechek');
INSERT INTO county VALUES (29,'Nandi','Mwingi Central','Chesumei','Kaptel/Kamoiywo'),
	(29,'Nandi','Mwingi Central','Chesumei','Kiptuya'),
	(29,'Nandi','Mwingi Central','Emgwen','Chepkumia'),
	(29,'Nandi','Mwingi Central','Emgwen','Kapkangani'),
	(29,'Nandi','Mwingi Central','Emgwen','Kapsabet'),
	(29,'Nandi','Mwingi Central','Emgwen','Kilibwoni'),
	(29,'Nandi','Mwingi Central','Mosop','Chepterwai'),
	(29,'Nandi','Mwingi Central','Mosop','Kipkaren'),
	(29,'Nandi','Mwingi Central','Mosop','Kurgung/ Surungai'),
	(29,'Nandi','Mwingi Central','Mosop','Kabiyet'),
	(29,'Nandi','Mwingi Central','Mosop','Ndalat'),
	(29,'Nandi','Mwingi Central','Mosop','Kabisaga'),
	(29,'Nandi','Mwingi Central','Mosop','Sangalo/Kebulonik'),
	(29,'Nandi','Mwingi Central','Nandi Hills','Nandi Hills'),
	(29,'Nandi','Mwingi Central','Nandi Hills','Chepkunyuk'),
	(29,'Nandi','Mwingi Central','Nandi Hills','Ol’lessos'),
	(29,'Nandi','Mwingi Central','Nandi Hills','Kapchorua'),
	(29,'Nandi','Mwingi Central','Tinderet','Songhor/Soba'),
	(29,'Nandi','Mwingi Central','Tinderet','Tindiret'),
	(29,'Nandi','Mwingi Central','Tinderet','Chemelil/Chemase'),
	(29,'Nandi','Mwingi Central','Tinderet','Kapsimotwo'),
	(30,'Baringo','Mwingi Central','Baringo Central','Kabarnet'),
	(30,'Baringo','Mwingi Central','Baringo Central','Sacho'),
	(30,'Baringo','Mwingi Central','Baringo Central','Tenges'),
	(30,'Baringo','Mwingi Central','Baringo Central','Ewalel/Chapcha'),
	(30,'Baringo','Mwingi Central','Baringo Central','Kapropita'),
	(30,'Baringo','Mwingi Central','Baringo North','Barwessa'),
	(30,'Baringo','Mwingi Central','Baringo North','Kabartonjo'),
	(30,'Baringo','Mwingi Central','Baringo North','Saimo/Kipsaraman'),
	(30,'Baringo','Mwingi Central','Baringo North','Saimo/Soi'),
	(30,'Baringo','Mwingi Central','Baringo North','Bartabwa'),
	(30,'Baringo','Mwingi Central','Baringo South','Marigat'),
	(30,'Baringo','Mwingi Central','Baringo South','Ilchamus'),
	(30,'Baringo','Mwingi Central','Baringo South','Mochongoi'),
	(30,'Baringo','Mwingi Central','Baringo South','Mukutani'),
	(30,'Baringo','Mwingi Central','Eldama Ravine','Lembus'),
	(30,'Baringo','Mwingi Central','Eldama Ravine','Lembus Kwen'),
	(30,'Baringo','Mwingi Central','Eldama Ravine','Ravine'),
	(30,'Baringo','Mwingi Central','Eldama Ravine','Mumberes/Maji Mazuri'),
	(30,'Baringo','Mwingi Central','Eldama Ravine','Lembus /Pekerra'),
	(30,'Baringo','Mwingi Central','Mogotio','Mogotio'),
	(30,'Baringo','Mwingi Central','Mogotio','Emining'),
	(30,'Baringo','Mwingi Central','Mogotio','Kisanana'),
	(30,'Baringo','Mwingi Central','Tiaty','Tirioko'),
	(30,'Baringo','Mwingi Central','Tiaty','Kolowa'),
	(30,'Baringo','Mwingi Central','Tiaty','Ribkwo'),
	(30,'Baringo','Mwingi Central','Tiaty','Silale'),
	(30,'Baringo','Mwingi Central','Tiaty','Loiyamorock'),
	(30,'Baringo','Mwingi Central','Tiaty','Tangulbei/Korossi'),
	(30,'Baringo','Mwingi Central','Tiaty','Churo/Amaya'),
	(31,'Laikipia','Mwingi Central','Laikipia North','Sosian'),
	(31,'Laikipia','Mwingi Central','Laikipia North','Segera'),
	(31,'Laikipia','Mwingi Central','Laikipia North','Mugogodo West'),
	(31,'Laikipia','Mwingi Central','Laikipia North','Mugogodo East'),
	(31,'Laikipia','Mwingi Central','Laikipia East','Ngobit'),
	(31,'Laikipia','Mwingi Central','Laikipia East','Tigithi'),
	(31,'Laikipia','Mwingi Central','Laikipia East','Thingithu'),
	(31,'Laikipia','Mwingi Central','Laikipia East','Nanyuki'),
	(31,'Laikipia','Mwingi Central','Laikipia East',' Umande'),
	(31,'Laikipia','Mwingi Central','Laikipia West','Ol-Moran'),
	(31,'Laikipia','Mwingi Central','Laikipia West','Rumuruti'),
	(31,'Laikipia','Mwingi Central','Laikipia West','Township '),
	(31,'Laikipia','Mwingi Central','Laikipia West','Githiga'),
	(31,'Laikipia','Mwingi Central','Laikipia West','Marmanet'),
	(31,'Laikipia','Mwingi Central','Laikipia West','Igwamiti Salama'),
	(32,'Nakuru','Mwingi Central','Nakuru Town East','Biashara'),
	(32,'Nakuru','Mwingi Central','Nakuru Town East','Kivumbini'),
	(32,'Nakuru','Mwingi Central','Nakuru Town East','Flamingo'),
	(32,'Nakuru','Mwingi Central','Nakuru Town East','Menengai'),
	(32,'Nakuru','Mwingi Central','Nakuru Town East','Nakuru East'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','Barut'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','London'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','Kaptembwo'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','Kapkures'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','Rhoda'),
	(32,'Nakuru','Mwingi Central','Nakuru Town West','Shaabab'),
	(32,'Nakuru','Mwingi Central','Njoro','Mau Narok'),
	(32,'Nakuru','Mwingi Central','Njoro','Mauche'),
	(32,'Nakuru','Mwingi Central','Njoro','Kihingo'),
	(32,'Nakuru','Mwingi Central','Njoro','Nessuit'),
	(32,'Nakuru','Mwingi Central','Njoro','Lare'),
	(32,'Nakuru','Mwingi Central','Njoro','Njoro'),
	(32,'Nakuru','Mwingi Central','Molo','Mariashoni'),
	(32,'Nakuru','Mwingi Central','Molo','Elburgon'),
	(32,'Nakuru','Mwingi Central','Molo','Turi'),
	(32,'Nakuru','Mwingi Central','Molo','Molo'),
	(32,'Nakuru','Mwingi Central','Gilgil','Gilgil'),
	(32,'Nakuru','Mwingi Central','Gilgil','Elementaita'),
	(32,'Nakuru','Mwingi Central','Gilgil','Mbaruk/Eburu'),
	(32,'Nakuru','Mwingi Central','Gilgil','Malewa West'),
	(32,'Nakuru','Mwingi Central','Gilgil','Murindati'),
	(32,'Nakuru','Mwingi Central','Naivasha','Biashara'),
	(32,'Nakuru','Mwingi Central','Naivasha','Hells Gate'),
	(32,'Nakuru','Mwingi Central','Naivasha','Lake View'),
	(32,'Nakuru','Mwingi Central','Naivasha','Maiella'),
	(32,'Nakuru','Mwingi Central','Naivasha','Mai Mahiu'),
	(32,'Nakuru','Mwingi Central','Naivasha','Olkaria'),
	(32,'Nakuru','Mwingi Central','Naivasha','Naivasha East'),
	(32,'Nakuru','Mwingi Central','Naivasha','Viwandani'),
	(32,'Nakuru','Mwingi Central','Kuresoi North','Kiptororo'),
	(32,'Nakuru','Mwingi Central','Kuresoi North','Nyota'),
	(32,'Nakuru','Mwingi Central','Kuresoi North','Sirikwa'),
	(32,'Nakuru','Mwingi Central','Kuresoi North','Kamara'),
	(32,'Nakuru','Mwingi Central','Kuresoi South','Amalo'),
	(32,'Nakuru','Mwingi Central','Kuresoi South','Keringet'),
	(32,'Nakuru','Mwingi Central','Kuresoi South','Kiptagich'),
	(32,'Nakuru','Mwingi Central','Kuresoi South','Tinet'),
	(32,'Nakuru','Mwingi Central','Bahati','Dundori'),
	(32,'Nakuru','Mwingi Central','Bahati','Kabatini'),
	(32,'Nakuru','Mwingi Central','Bahati','Kiamaina'),
	(32,'Nakuru','Mwingi Central','Bahati','Lanet/Umoja'),
	(32,'Nakuru','Mwingi Central','Bahati','Bahati'),
	(32,'Nakuru','Mwingi Central','Rongai','Menengai West'),
	(32,'Nakuru','Mwingi Central','Rongai','Soin'),
	(32,'Nakuru','Mwingi Central','Rongai','Visoi'),
	(32,'Nakuru','Mwingi Central','Rongai','Mosop'),
	(32,'Nakuru','Mwingi Central','Rongai','Solai'),
	(32,'Nakuru','Mwingi Central','Subukia','Subukia'),
	(32,'Nakuru','Mwingi Central','Subukia','Waseges'),
	(32,'Nakuru','Mwingi Central','Subukia','Kabazi'),
	(33,'Narok','Mwingi Central','Narok North','Olpusimoru'),
	(33,'Narok','Mwingi Central','Narok North','Olokurto'),
	(33,'Narok','Mwingi Central','Narok North','Narok Town'),
	(33,'Narok','Mwingi Central','Narok North','Nkareta''Olorropil'),
	(33,'Narok','Mwingi Central','Narok North','Melili'),
	(33,'Narok','Mwingi Central','Narok South','Majimoto/Naroos'),
	(33,'Narok','Mwingi Central','Narok South','Uraololulung’a'),
	(33,'Narok','Mwingi Central','Narok South','Melelo'),
	(33,'Narok','Mwingi Central','Narok South','Loita'),
	(33,'Narok','Mwingi Central','Narok South','Sogoo'),
	(33,'Narok','Mwingi Central','Narok South','Sagamian'),
	(33,'Narok','Mwingi Central','Narok East','Mosiro'),
	(33,'Narok','Mwingi Central','Narok East','Ildamat'),
	(33,'Narok','Mwingi Central','Narok East','Keekonyokie'),
	(33,'Narok','Mwingi Central','Narok East','Suswa'),
	(33,'Narok','Mwingi Central','Narok West','Ilmotiok'),
	(33,'Narok','Mwingi Central','Narok West','Mara'),
	(33,'Narok','Mwingi Central','Narok West','Siana'),
	(33,'Narok','Mwingi Central','Narok West','Naikarra'),
	(33,'Narok','Mwingi Central','Kilgoris','Kilgoris Central'),
	(33,'Narok','Mwingi Central','Kilgoris','Keyian'),
	(33,'Narok','Mwingi Central','Kilgoris','Angata Barikoi'),
	(33,'Narok','Mwingi Central','Kilgoris','Shankoe'),
	(33,'Narok','Mwingi Central','Kilgoris','Kimintet'),
	(33,'Narok','Mwingi Central','Kilgoris','Lolgorian'),
	(33,'Narok','Mwingi Central','Emurua Dikirr','Ilkerin'),
	(33,'Narok','Mwingi Central','Emurua Dikirr','Ololmasani'),
	(33,'Narok','Mwingi Central','Emurua Dikirr','Mogondo'),
	(33,'Narok','Mwingi Central','Emurua Dikirr','Kapsasian'),
	(34,'Kajiado','Mwingi Central','Kajiado Central','Purko'),
	(34,'Kajiado','Mwingi Central','Kajiado Central','Ildamat'),
	(34,'Kajiado','Mwingi Central','Kajiado Central','Dalalekutuk'),
	(34,'Kajiado','Mwingi Central','Kajiado Central','Matapato North'),
	(34,'Kajiado','Mwingi Central','Kajiado Central','Matapato South'),
	(34,'Kajiado','Mwingi Central','Kajiado East','Kaputiei North'),
	(34,'Kajiado','Mwingi Central','Kajiado East','Kitengela'),
	(34,'Kajiado','Mwingi Central','Kajiado East','Oloosirkon/Sholinke'),
	(34,'Kajiado','Mwingi Central','Kajiado East','Kenyawa-Poka'),
	(34,'Kajiado','Mwingi Central','Kajiado East','Imaroro'),
	(34,'Kajiado','Mwingi Central','Kajiado North','Olkeri'),
	(34,'Kajiado','Mwingi Central','Kajiado North','Ongata Rongai'),
	(34,'Kajiado','Mwingi Central','Kajiado North','Nkaimurunya'),
	(34,'Kajiado','Mwingi Central','Kajiado North','Oloolua'),
	(34,'Kajiado','Mwingi Central','Kajiado North','Ngong'),
	(34,'Kajiado','Mwingi Central','Kajiado West','  Keekonyokie'),
	(34,'Kajiado','Mwingi Central','Kajiado West','Iloodokilani'),
	(34,'Kajiado','Mwingi Central','Kajiado West','Magadi'),
	(34,'Kajiado','Mwingi Central','Kajiado West','Ewuaso Oonkidong’i'),
	(34,'Kajiado','Mwingi Central','Kajiado West','Mosiro'),
	(34,'Kajiado','Mwingi Central','Kajiado South','Entonet/Lenkisi'),
	(34,'Kajiado','Mwingi Central','Kajiado South','Mbirikani/Eselen'),
	(34,'Kajiado','Mwingi Central','Kajiado South','Keikuku'),
	(34,'Kajiado','Mwingi Central','Kajiado South','Rombo'),
	(34,'Kajiado','Mwingi Central','Kajiado South','Kimana'),
	(35,'Kericho','Mwingi Central','Ainamoi','Kapsoit'),
	(35,'Kericho','Mwingi Central','Ainamoi','Ainamoi'),
	(35,'Kericho','Mwingi Central','Ainamoi','Kipchebor'),
	(35,'Kericho','Mwingi Central','Ainamoi','Kapkugerwet'),
	(35,'Kericho','Mwingi Central','Ainamoi','Kipchimchim'),
	(35,'Kericho','Mwingi Central','Ainamoi','Kapsaos'),
	(35,'Kericho','Mwingi Central','Belgut','Waldai'),
	(35,'Kericho','Mwingi Central','Belgut','Kabianga'),
	(35,'Kericho','Mwingi Central','Belgut','Cheptororiet/Seretut'),
	(35,'Kericho','Mwingi Central','Belgut','Chaik'),
	(35,'Kericho','Mwingi Central','Belgut','Kapsuser'),
	(35,'Kericho','Mwingi Central','Bureti','Kisiara'),
	(35,'Kericho','Mwingi Central','Bureti','Tebesonik'),
	(35,'Kericho','Mwingi Central','Bureti','Cheboin'),
	(35,'Kericho','Mwingi Central','Bureti','Chemosot'),
	(35,'Kericho','Mwingi Central','Bureti','Litein'),
	(35,'Kericho','Mwingi Central','Bureti','Cheplanget'),
	(35,'Kericho','Mwingi Central','Bureti','Kapkatet'),
	(35,'Kericho','Mwingi Central','Kipkelion East','Londiani'),
	(35,'Kericho','Mwingi Central','Kipkelion East','Kedowa/Kimugul'),
	(35,'Kericho','Mwingi Central','Kipkelion East','Chepseon'),
	(35,'Kericho','Mwingi Central','Kipkelion East','Tendeno/Sorget'),
	(35,'Kericho','Mwingi Central','Kipkelion West','Kunyak'),
	(35,'Kericho','Mwingi Central','Kipkelion West','Kamasian'),
	(35,'Kericho','Mwingi Central','Kipkelion West','Kipkelion'),
	(35,'Kericho','Mwingi Central','Kipkelion West','Chilchila'),
	(35,'Kericho','Mwingi Central','Soin Sigowet','Sigowet'),
	(35,'Kericho','Mwingi Central','Soin Sigowet','Kaplelartet'),
	(35,'Kericho','Mwingi Central','Soin Sigowet','Soliat'),
	(35,'Kericho','Mwingi Central','Soin Sigowet','Soin'),
	(36,'Bomet','Mwingi Central','Sotik','Ndanai/Abosi'),
	(36,'Bomet','Mwingi Central','Sotik','Chemagel'),
	(36,'Bomet','Mwingi Central','Sotik','Kipsonoi'),
	(36,'Bomet','Mwingi Central','Sotik','Apletundo'),
	(36,'Bomet','Mwingi Central','Sotik','Rongena/Manare T'),
	(36,'Bomet','Mwingi Central','Bomet Central','Silibwet Township'),
	(36,'Bomet','Mwingi Central','Bomet Central','Ndaraweta'),
	(36,'Bomet','Mwingi Central','Bomet Central',' Singorwet'),
	(36,'Bomet','Mwingi Central','Bomet Central','Chesoen'),
	(36,'Bomet','Mwingi Central','Bomet Central','Mutarakwa'),
	(36,'Bomet','Mwingi Central','Bomet East','Merigi'),
	(36,'Bomet','Mwingi Central','Bomet East','Kembu'),
	(36,'Bomet','Mwingi Central','Bomet East','Longisa'),
	(36,'Bomet','Mwingi Central','Bomet East','Kipreres'),
	(36,'Bomet','Mwingi Central','Bomet East','Chemaner'),
	(36,'Bomet','Mwingi Central','Chepalungu','  Kong’asis'),
	(36,'Bomet','Mwingi Central','Chepalungu',' Nyangores'),
	(36,'Bomet','Mwingi Central','Chepalungu','Sigor'),
	(36,'Bomet','Mwingi Central','Chepalungu',' Chebunyo'),
	(36,'Bomet','Mwingi Central','Chepalungu','Siongiroi'),
	(36,'Bomet','Mwingi Central','Konoin','Chepchabas'),
	(36,'Bomet','Mwingi Central','Konoin','Kimulot'),
	(36,'Bomet','Mwingi Central','Konoin','Mogogosiek'),
	(36,'Bomet','Mwingi Central','Konoin','Boito'),
	(36,'Bomet','Mwingi Central','Konoin',' Embomos'),
	(37,'Kakamega','Mwingi Central','Butere','Marama West'),
	(37,'Kakamega','Mwingi Central','Butere','Marama Central'),
	(37,'Kakamega','Mwingi Central','Butere','Marenyo-Shianda'),
	(37,'Kakamega','Mwingi Central','Butere','Maram North'),
	(37,'Kakamega','Mwingi Central','Butere','Marama South'),
	(37,'Kakamega','Mwingi Central','Ikolomani','Idakho South'),
	(37,'Kakamega','Mwingi Central','Ikolomani','Idakho East'),
	(37,'Kakamega','Mwingi Central','Ikolomani','Idakho North'),
	(37,'Kakamega','Mwingi Central','Ikolomani','Idakho Central'),
	(37,'Kakamega','Mwingi Central','Khwisero','Kisa North'),
	(37,'Kakamega','Mwingi Central','Khwisero','Kisa East'),
	(37,'Kakamega','Mwingi Central','Khwisero','Kisa West'),
	(37,'Kakamega','Mwingi Central','Khwisero','Kisa Central'),
	(37,'Kakamega','Mwingi Central','Lurambi','Butsotso East'),
	(37,'Kakamega','Mwingi Central','Lurambi','Butsotso South'),
	(37,'Kakamega','Mwingi Central','Lurambi','Butsotso Central'),
	(37,'Kakamega','Mwingi Central','Lurambi','Sheywe'),
	(37,'Kakamega','Mwingi Central','Lurambi','Mahiakalo'),
	(37,'Kakamega','Mwingi Central','Lurambi','Shirere'),
	(37,'Kakamega','Mwingi Central','Likuyani','Likuyani'),
	(37,'Kakamega','Mwingi Central','Likuyani','Sango');
INSERT INTO county VALUES (37,'Kakamega','Mwingi Central','Likuyani','Kongoni'),
	(37,'Kakamega','Mwingi Central','Likuyani','Nzoia'),
	(37,'Kakamega','Mwingi Central','Likuyani','Sinoko'),
	(37,'Kakamega','Mwingi Central','Malava','West Kabras'),
	(37,'Kakamega','Mwingi Central','Malava','Chemuche East'),
	(37,'Kakamega','Mwingi Central','Malava','Kabras'),
	(37,'Kakamega','Mwingi Central','Malava','Butali/Chegulo'),
	(37,'Kakamega','Mwingi Central','Malava','Manda-Shivanga'),
	(37,'Kakamega','Mwingi Central','Malava','Shirugu-Mugai'),
	(37,'Kakamega','Mwingi Central','Malava','South Kabras'),
	(37,'Kakamega','Mwingi Central','Matungu','Koyonzo'),
	(37,'Kakamega','Mwingi Central','Matungu','Kholera'),
	(37,'Kakamega','Mwingi Central','Matungu','Khalaba'),
	(37,'Kakamega','Mwingi Central','Matungu','Mayoni'),
	(37,'Kakamega','Mwingi Central','Matungu','Namamali'),
	(37,'Kakamega','Mwingi Central','Mumias East','Lusheya/Lubinu'),
	(37,'Kakamega','Mwingi Central','Mumias East','Malaha/Isongo/Makunga'),
	(37,'Kakamega','Mwingi Central','Mumias East','East Wanga'),
	(37,'Kakamega','Mwingi Central','Mumias West','Mumias Central'),
	(37,'Kakamega','Mwingi Central','Mumias West','Mumias North'),
	(37,'Kakamega','Mwingi Central','Mumias West','Etenje'),
	(37,'Kakamega','Mwingi Central','Mumias West','Musanda'),
	(37,'Kakamega','Mwingi Central','Navakholo','Ingostse-Mathia'),
	(37,'Kakamega','Mwingi Central','Navakholo','Shinoyi-Shikomari'),
	(37,'Kakamega','Mwingi Central','Navakholo','Esumeyia'),
	(37,'Kakamega','Mwingi Central','Navakholo','Bunyala West'),
	(37,'Kakamega','Mwingi Central','Navakholo','Bunyal East'),
	(37,'Kakamega','Mwingi Central','Navakholo','Bunyala Central'),
	(37,'Kakamega','Mwingi Central','Lugari','Mautuma'),
	(37,'Kakamega','Mwingi Central','Lugari','Lugari'),
	(37,'Kakamega','Mwingi Central','Lugari','Lumakanda'),
	(37,'Kakamega','Mwingi Central','Lugari','Chekalini'),
	(37,'Kakamega','Mwingi Central','Lugari','Chevaywa'),
	(37,'Kakamega','Mwingi Central','Lugari','Lawandeti'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Mautuma'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Lugari'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Lumakanda'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Chekalini'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Chevaywa'),
	(37,'Kakamega','Mwingi Central','Shinyalu','Lawandeti'),
	(38,'Vihiga','Mwingi Central','Emuhaya','North East Bunyore'),
	(38,'Vihiga','Mwingi Central','Emuhaya','Central Bunyore'),
	(38,'Vihiga','Mwingi Central','Emuhaya','West Bunyore'),
	(38,'Vihiga','Mwingi Central','Hamisi','Shiru'),
	(38,'Vihiga','Mwingi Central','Hamisi','Gisambai'),
	(38,'Vihiga','Mwingi Central','Hamisi','Shamakhokho'),
	(38,'Vihiga','Mwingi Central','Hamisi','Banja'),
	(38,'Vihiga','Mwingi Central','Hamisi','Muhudi'),
	(38,'Vihiga','Mwingi Central','Hamisi','Tambaa'),
	(38,'Vihiga','Mwingi Central','Hamisi','Jepkoyai'),
	(38,'Vihiga','Mwingi Central','Sabatia','Lyaduywa/Izava'),
	(38,'Vihiga','Mwingi Central','Sabatia','West Sabatia'),
	(38,'Vihiga','Mwingi Central','Sabatia','Chavakali'),
	(38,'Vihiga','Mwingi Central','Sabatia','North Maragoli'),
	(38,'Vihiga','Mwingi Central','Sabatia','Wodanga'),
	(38,'Vihiga','Mwingi Central','Sabatia','Busali'),
	(38,'Vihiga','Mwingi Central','Vihiga','Lugaga-Wamuluma'),
	(38,'Vihiga','Mwingi Central','Vihiga','South Maragoli'),
	(38,'Vihiga','Mwingi Central','Vihiga','Central Maragoli'),
	(38,'Vihiga','Mwingi Central','Vihiga','Mungoma'),
	(38,'Vihiga','Mwingi Central','Luanda','Luanda Township'),
	(38,'Vihiga','Mwingi Central','Luanda','Wemilabi'),
	(38,'Vihiga','Mwingi Central','Luanda','Mwibona'),
	(38,'Vihiga','Mwingi Central','Luanda','Luanda South'),
	(38,'Vihiga','Mwingi Central','Luanda','Emabungo'),
	(39,'Bungoma','Mwingi Central','Bumula','Bumula'),
	(39,'Bungoma','Mwingi Central','Bumula','Khasoko'),
	(39,'Bungoma','Mwingi Central','Bumula','Kabula'),
	(39,'Bungoma','Mwingi Central','Bumula','Kimaeti'),
	(39,'Bungoma','Mwingi Central','Bumula','South Bukusu'),
	(39,'Bungoma','Mwingi Central','Bumula','Siboti'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Bukembe West'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Bukembe East'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Township'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Khalaba'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Musikoma'),
	(39,'Bungoma','Mwingi Central','Kanduyi','East Snag’alo'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Marakatu'),
	(39,'Bungoma','Mwingi Central','Kanduyi','Tuuti'),
	(39,'Bungoma','Mwingi Central','Kanduyi','West Sang’alo'),
	(39,'Bungoma','Mwingi Central','Webuye East','Mihuu'),
	(39,'Bungoma','Mwingi Central','Webuye East','Ndivisi'),
	(39,'Bungoma','Mwingi Central','Webuye East','Maraka'),
	(39,'Bungoma','Mwingi Central','Webuye West','Sitikho'),
	(39,'Bungoma','Mwingi Central','Webuye West','Matulo'),
	(39,'Bungoma','Mwingi Central','Webuye West','Bokoli'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Cheptais'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Chesikaki'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Chepyuk'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Kapkateny'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Kaptama'),
	(39,'Bungoma','Mwingi Central','Mt. Elgon','Elgon'),
	(39,'Bungoma','Mwingi Central','Sirisia','Namwela'),
	(39,'Bungoma','Mwingi Central','Sirisia','Malakisi/South Kulisiru'),
	(39,'Bungoma','Mwingi Central','Sirisia','Lwandanyi'),
	(39,'Bungoma','Mwingi Central','Tongaren','Mbakalo'),
	(39,'Bungoma','Mwingi Central','Tongaren','Naitiri/Kabuyefwe'),
	(39,'Bungoma','Mwingi Central','Tongaren','Milima'),
	(39,'Bungoma','Mwingi Central','Tongaren','Ndalu/Tabani'),
	(39,'Bungoma','Mwingi Central','Tongaren','Tongaren'),
	(39,'Bungoma','Mwingi Central','Tongaren','Soysambu/Mitua'),
	(39,'Bungoma','Mwingi Central','Kabuchai','Kabuchai/Chwele'),
	(39,'Bungoma','Mwingi Central','Kabuchai','West Nalondo'),
	(39,'Bungoma','Mwingi Central','Kabuchai','Bwake/Luuya'),
	(39,'Bungoma','Mwingi Central','Kabuchai','Mukuyuni'),
	(39,'Bungoma','Mwingi Central','Kabuchai','South Bukusu'),
	(39,'Bungoma','Mwingi Central','Kimilili','Kibingei'),
	(39,'Bungoma','Mwingi Central','Kimilili','Kimilili'),
	(39,'Bungoma','Mwingi Central','Kimilili','Maeni'),
	(39,'Bungoma','Mwingi Central','Kimilili','Kamukuywa'),
	(40,'Busia','Mwingi Central','Teso North','MALABA CENTRAL'),
	(40,'Busia','Mwingi Central','Teso North','MALABA NORTH'),
	(40,'Busia','Mwingi Central','Teso North','ANG’URAI SOUTH'),
	(40,'Busia','Mwingi Central','Teso North','MALABA SOUTH'),
	(40,'Busia','Mwingi Central','Teso North','ANG’URAI NORTH'),
	(40,'Busia','Mwingi Central','Teso North','ANG’URAI EAST'),
	(40,'Busia','Mwingi Central','Teso South','ANG''OROM'),
	(40,'Busia','Mwingi Central','Teso South','CHAKOI SOUTH'),
	(40,'Busia','Mwingi Central','Teso South','AMUKURA CENTRAL'),
	(40,'Busia','Mwingi Central','Teso South','CHAKOI NORTH'),
	(40,'Busia','Mwingi Central','Teso South','AMUKURA EAST'),
	(40,'Busia','Mwingi Central','Teso South','AMUKURA WEST'),
	(40,'Busia','Mwingi Central','Nambale','NAMBALE TOWNSHIP'),
	(40,'Busia','Mwingi Central','Nambale','BUKHAYO NORTH/WALTSI'),
	(40,'Busia','Mwingi Central','Nambale','BUKHAYO EAST'),
	(40,'Busia','Mwingi Central','Nambale','BUKHAYO CENTRAL'),
	(40,'Busia','Mwingi Central','Matayos','BUKHAYO WEST'),
	(40,'Busia','Mwingi Central','Matayos','MAYENJE'),
	(40,'Busia','Mwingi Central','Matayos','MATAYOS SOUTHBUSIBWABO'),
	(40,'Busia','Mwingi Central','Matayos','BURUMBA'),
	(40,'Busia','Mwingi Central','Butula','MARACHI WESTKINGANDOLE'),
	(40,'Busia','Mwingi Central','Butula','MARACHI CENTRAL'),
	(40,'Busia','Mwingi Central','Butula','MARACHI EAST'),
	(40,'Busia','Mwingi Central','Butula','MARACHI NORTH'),
	(40,'Busia','Mwingi Central','Butula','ELUGULU'),
	(40,'Busia','Mwingi Central','Funyula','NAMBOBOTO NAMBUKU'),
	(40,'Busia','Mwingi Central','Funyula','NANGINA'),
	(40,'Busia','Mwingi Central','Funyula','AGENG''A NANGUBA'),
	(40,'Busia','Mwingi Central','Funyula','BWIRI'),
	(41,'Siaya','Mwingi Central','Alego Usonga','Usonga'),
	(41,'Siaya','Mwingi Central','Alego Usonga','West Alego'),
	(41,'Siaya','Mwingi Central','Alego Usonga','Central Alego'),
	(41,'Siaya','Mwingi Central','Alego Usonga','Siaya Township'),
	(41,'Siaya','Mwingi Central','Alego Usonga','North Alego'),
	(41,'Siaya','Mwingi Central','Alego Usonga','South East Alego'),
	(41,'Siaya','Mwingi Central','Gem','North Gem'),
	(41,'Siaya','Mwingi Central','Gem','West Gem'),
	(41,'Siaya','Mwingi Central','Gem','Central Gem'),
	(41,'Siaya','Mwingi Central','Gem','Yala Township'),
	(41,'Siaya','Mwingi Central','Gem','East Gem'),
	(41,'Siaya','Mwingi Central','Gem','South Gem'),
	(41,'Siaya','Mwingi Central','Bondo','West Yimbo'),
	(41,'Siaya','Mwingi Central','Bondo','Central Sakwa'),
	(41,'Siaya','Mwingi Central','Bondo','South Sakwa'),
	(41,'Siaya','Mwingi Central','Bondo','Yimbo East'),
	(41,'Siaya','Mwingi Central','Bondo','West Sakwa'),
	(41,'Siaya','Mwingi Central','Bondo','North Sakwa'),
	(41,'Siaya','Mwingi Central','Rarieda','Gem Rae'),
	(41,'Siaya','Mwingi Central','Rarieda','East Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','West Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','Central Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','South West Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','North West Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','North East Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','South East Asembo'),
	(41,'Siaya','Mwingi Central','Rarieda','Nyang''oma Kogelo'),
	(41,'Siaya','Mwingi Central','Rarieda','West Uyoma'),
	(41,'Siaya','Mwingi Central','Rarieda','Central Uyoma'),
	(41,'Siaya','Mwingi Central','Rarieda','North Uyoma'),
	(41,'Siaya','Mwingi Central','Ugenya','East Asembo'),
	(41,'Siaya','Mwingi Central','Ugenya','West Asembo'),
	(41,'Siaya','Mwingi Central','Ugenya','North Uyoma'),
	(41,'Siaya','Mwingi Central','Ugenya','South Uyoma'),
	(41,'Siaya','Mwingi Central','Ugenya','West Uyoma'),
	(41,'Siaya','Mwingi Central','Ugunja','Sidindi'),
	(41,'Siaya','Mwingi Central','Ugunja','Sigomere'),
	(41,'Siaya','Mwingi Central','Ugunja','Ugunja'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Railways'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Migosi'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Shaurimoyo Kaloleni'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Market Milimani'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Kondele'),
	(42,'Kisumu','Mwingi Central','Kisumu Central','Nyalenda B'),
	(42,'Kisumu','Mwingi Central','Kisumu East','Kajulu'),
	(42,'Kisumu','Mwingi Central','Kisumu East','Kolwa East'),
	(42,'Kisumu','Mwingi Central','Kisumu East','Manyatta ''B'''),
	(42,'Kisumu','Mwingi Central','Kisumu East','Nyalenda ''A'''),
	(42,'Kisumu','Mwingi Central','Kisumu East','Kolwa Central'),
	(42,'Kisumu','Mwingi Central','Kisumu West','South West Kisumu'),
	(42,'Kisumu','Mwingi Central','Kisumu West','Cetral Kisumu'),
	(42,'Kisumu','Mwingi Central','Kisumu West','Kisumu North'),
	(42,'Kisumu','Mwingi Central','Kisumu West','West Kisumu'),
	(42,'Kisumu','Mwingi Central','Kisumu West','North West Kisumu'),
	(42,'Kisumu','Mwingi Central','Seme','West Seme'),
	(42,'Kisumu','Mwingi Central','Seme','Central Seme'),
	(42,'Kisumu','Mwingi Central','Seme','East Seme'),
	(42,'Kisumu','Mwingi Central','Seme','North Seme'),
	(42,'Kisumu','Mwingi Central','Nyando','East Kano/Waidhi'),
	(42,'Kisumu','Mwingi Central','Nyando','Awasi/Onjiko'),
	(42,'Kisumu','Mwingi Central','Nyando','Ahero'),
	(42,'Kisumu','Mwingi Central','Nyando','Kabonyo/Kanyag Wal'),
	(42,'Kisumu','Mwingi Central','Nyando','Kobura'),
	(42,'Kisumu','Mwingi Central','Muhoroni','Miwani'),
	(42,'Kisumu','Mwingi Central','Muhoroni','Ombeyi'),
	(42,'Kisumu','Mwingi Central','Muhoroni','Masogo/Nyag’oma'),
	(42,'Kisumu','Mwingi Central','Muhoroni','Chemeli/Muhoroni/Koru'),
	(42,'Kisumu','Mwingi Central','Nyakach','South East Nyakach'),
	(42,'Kisumu','Mwingi Central','Nyakach','West Nyakach'),
	(42,'Kisumu','Mwingi Central','Nyakach','North Nyakach'),
	(42,'Kisumu','Mwingi Central','Nyakach','Central Nyakach'),
	(42,'Kisumu','Mwingi Central','Nyakach','South West Nyakach'),
	(43,'Homa Bay','Mwingi Central','Homa Bay Town','Homa Bay Central'),
	(43,'Homa Bay','Mwingi Central','Homa Bay Town','Homa Bay Arujo'),
	(43,'Homa Bay','Mwingi Central','Homa Bay Town','Homa Bay West'),
	(43,'Homa Bay','Mwingi Central','Homa Bay Town','Homa Bay East'),
	(43,'Homa Bay','Mwingi Central','Kabondo Kasipul','Kabondo East'),
	(43,'Homa Bay','Mwingi Central','Kabondo Kasipul','Kabondo West'),
	(43,'Homa Bay','Mwingi Central','Kabondo Kasipul','Kokwanyo'),
	(43,'Homa Bay','Mwingi Central','Kabondo Kasipul','Kakelo-Kojwach'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','West Karachuonyo'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','North Karachuonyo'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','Central Kanyaluo'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','Kibiri'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','Wangchieng'),
	(43,'Homa Bay','Mwingi Central','Karachuonyo','Kendu Bay Town'),
	(43,'Homa Bay','Mwingi Central','Kasipul','West Kasipul'),
	(43,'Homa Bay','Mwingi Central','Kasipul','South Kasipul'),
	(43,'Homa Bay','Mwingi Central','Kasipul','Central Kasipul'),
	(43,'Homa Bay','Mwingi Central','Kasipul','East Kamagak'),
	(43,'Homa Bay','Mwingi Central','Kasipul','West Kamagak'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kwabwai'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kanyadoto'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kanyikela'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kabuoch North'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kabuoch South/Pala'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kanyamwa Kologi'),
	(43,'Homa Bay','Mwingi Central','Ndhiwa','Kanyamwa Kosewe'),
	(43,'Homa Bay','Mwingi Central','Rangwe','West Gem'),
	(43,'Homa Bay','Mwingi Central','Rangwe','East Gem'),
	(43,'Homa Bay','Mwingi Central','Rangwe','Kagan'),
	(43,'Homa Bay','Mwingi Central','Rangwe','Kochia'),
	(43,'Homa Bay','Mwingi Central','Suba North','Mfangano Island'),
	(43,'Homa Bay','Mwingi Central','Suba North','Rusinga Island'),
	(43,'Homa Bay','Mwingi Central','Suba North','Kasgunga'),
	(43,'Homa Bay','Mwingi Central','Suba North','Gember'),
	(43,'Homa Bay','Mwingi Central','Suba North','Lambwe'),
	(43,'Homa Bay','Mwingi Central','Suba South','Gwassi South'),
	(43,'Homa Bay','Mwingi Central','Suba South','Gwassi North'),
	(43,'Homa Bay','Mwingi Central','Suba South','Kaksingri West'),
	(43,'Homa Bay','Mwingi Central','Suba South','Ruma-Kakshingri');
INSERT INTO county VALUES (44,'Migori','Mwingi Central','Rongo','North Kamagambo'),
	(44,'Migori','Mwingi Central','Rongo','Central Kamagambo'),
	(44,'Migori','Mwingi Central','Rongo','East Kamagambo'),
	(44,'Migori','Mwingi Central','Rongo','South Kamagambo'),
	(44,'Migori','Mwingi Central','Awendo','North East Sakwa'),
	(44,'Migori','Mwingi Central','Awendo','South Sakwa'),
	(44,'Migori','Mwingi Central','Awendo','West Sakwa'),
	(44,'Migori','Mwingi Central','Awendo','Central Sakwa'),
	(44,'Migori','Mwingi Central','Suna East','God Jope'),
	(44,'Migori','Mwingi Central','Suna East','Suna Central'),
	(44,'Migori','Mwingi Central','Suna East','Kakrao'),
	(44,'Migori','Mwingi Central','Suna East','Kwa'),
	(44,'Migori','Mwingi Central','Suna West','Wiga'),
	(44,'Migori','Mwingi Central','Suna West','Wasweta II'),
	(44,'Migori','Mwingi Central','Suna West','Ragan-Oruba'),
	(44,'Migori','Mwingi Central','Suna West','Wasimbete'),
	(44,'Migori','Mwingi Central','Uriri','West Kanyamkago'),
	(44,'Migori','Mwingi Central','Uriri','North Kanyamkago'),
	(44,'Migori','Mwingi Central','Uriri','Central Kanyam Kago'),
	(44,'Migori','Mwingi Central','Uriri','South Kanyamkago'),
	(44,'Migori','Mwingi Central','Uriri','East Kanyamkago'),
	(44,'Migori','Mwingi Central','Nyatike','Kachien’g'),
	(44,'Migori','Mwingi Central','Nyatike','Kanyasa'),
	(44,'Migori','Mwingi Central','Nyatike','North Kadem'),
	(44,'Migori','Mwingi Central','Nyatike','Macalder/ Kanyarwanda'),
	(44,'Migori','Mwingi Central','Nyatike','Kaler'),
	(44,'Migori','Mwingi Central','Nyatike','Got Kachola'),
	(44,'Migori','Mwingi Central','Nyatike','Muhuru'),
	(44,'Migori','Mwingi Central','Kuria East','Gokeharaka/Getamwega'),
	(44,'Migori','Mwingi Central','Kuria East','Ntimaru West'),
	(44,'Migori','Mwingi Central','Kuria East','Ntimaru East'),
	(44,'Migori','Mwingi Central','Kuria East','Nyabasi East'),
	(44,'Migori','Mwingi Central','Kuria East','Nyabasi West'),
	(44,'Migori','Mwingi Central','Kuria West','Bukira East'),
	(44,'Migori','Mwingi Central','Kuria West','Bukira Central/ Ikerege'),
	(44,'Migori','Mwingi Central','Kuria West','Isibania'),
	(44,'Migori','Mwingi Central','Kuria West','Makerero'),
	(44,'Migori','Mwingi Central','Kuria West','Masaba'),
	(44,'Migori','Mwingi Central','Kuria West','Tagare'),
	(44,'Migori','Mwingi Central','Kuria West','Nyamosense/Ko Mosoko'),
	(45,'Kisii','Mwingi Central','Kitutu Chache North','MONYERERO'),
	(45,'Kisii','Mwingi Central','Kitutu Chache North','SENSI'),
	(45,'Kisii','Mwingi Central','Kitutu Chache North','MARANI'),
	(45,'Kisii','Mwingi Central','Kitutu Chache North','MWAMONARI'),
	(45,'Kisii','Mwingi Central','Kitutu Chache South','BOGUSERO'),
	(45,'Kisii','Mwingi Central','Kitutu Chache South','BOGEKA'),
	(45,'Kisii','Mwingi Central','Kitutu Chache South','NYAKOE'),
	(45,'Kisii','Mwingi Central','Kitutu Chache South','KITUTU CENTRAL'),
	(45,'Kisii','Mwingi Central','Kitutu Chache South','NYATIEKO'),
	(45,'Kisii','Mwingi Central','Nyaribari Masaba','ICHUNI'),
	(45,'Kisii','Mwingi Central','Nyaribari Masaba','NYAMASIBI'),
	(45,'Kisii','Mwingi Central','Nyaribari Masaba','MASIMBA'),
	(45,'Kisii','Mwingi Central','Nyaribari Masaba','GESUSU'),
	(45,'Kisii','Mwingi Central','Nyaribari Masaba','KIAMOKAMA'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','BOBARACHO'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','KISII CENTRAL'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','KEUMBU'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','KIOGORO'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','BIRONGO'),
	(45,'Kisii','Mwingi Central','Nyaribari Chache','IBENO'),
	(45,'Kisii','Mwingi Central','Bomachoge Borabu','BORABU MASABA'),
	(45,'Kisii','Mwingi Central','Bomachoge Borabu','BOOCHI BORABU'),
	(45,'Kisii','Mwingi Central','Bomachoge Borabu','BOKIMONGE'),
	(45,'Kisii','Mwingi Central','Bomachoge Borabu','MAGENCHE'),
	(45,'Kisii','Mwingi Central','Bomachoge Chache','MAJOGE BASI'),
	(45,'Kisii','Mwingi Central','Bomachoge Chache','BOOCHI/TENDERE'),
	(45,'Kisii','Mwingi Central','Bomachoge Chache','BOSOTI/SENGERA'),
	(45,'Kisii','Mwingi Central','Bobasi','MASIGE WEST'),
	(45,'Kisii','Mwingi Central','Bobasi','MASIG EAST'),
	(45,'Kisii','Mwingi Central','Bobasi','BASI CENTRAL'),
	(45,'Kisii','Mwingi Central','Bobasi','NYACHEKI'),
	(45,'Kisii','Mwingi Central','Bobasi','BASSI BOGETAORIO'),
	(45,'Kisii','Mwingi Central','Bobasi','BOBASI CHACHE'),
	(45,'Kisii','Mwingi Central','Bobasi','SAMETA/ MOKWERERO'),
	(45,'Kisii','Mwingi Central','Bobasi','BOBASI/ BOITANGARE'),
	(45,'Kisii','Mwingi Central','South Mugirango','BOGETENGA'),
	(45,'Kisii','Mwingi Central','South Mugirango','BORABU/CHITAGO'),
	(45,'Kisii','Mwingi Central','South Mugirango','MOTICHO'),
	(45,'Kisii','Mwingi Central','South Mugirango','GETENGA'),
	(45,'Kisii','Mwingi Central','South Mugirango','TABAKA'),
	(45,'Kisii','Mwingi Central','South Mugirango','BOIKANGA'),
	(45,'Kisii','Mwingi Central','Bonchari','BOMARIBA'),
	(45,'Kisii','Mwingi Central','Bonchari','BOGIAKUMU'),
	(45,'Kisii','Mwingi Central','Bonchari','BOKEIRA'),
	(45,'Kisii','Mwingi Central','Bonchari','RIANA'),
	(46,'Nyamira','Mwingi Central','Borabu','Mekenene'),
	(46,'Nyamira','Mwingi Central','Borabu','Kiabonyoru'),
	(46,'Nyamira','Mwingi Central','Borabu','Esise'),
	(46,'Nyamira','Mwingi Central','Borabu','Nyansiongo'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Rigoma'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Gachuba'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Kemera'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Magombo'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Manga'),
	(46,'Nyamira','Mwingi Central','Kitutu Masaba','Gesima'),
	(46,'Nyamira','Mwingi Central','West Mugirango','Nyamaiya'),
	(46,'Nyamira','Mwingi Central','West Mugirango','Bogichora'),
	(46,'Nyamira','Mwingi Central','West Mugirango','Bosamaro'),
	(46,'Nyamira','Mwingi Central','West Mugirango','Bonyamatuta'),
	(46,'Nyamira','Mwingi Central','West Mugirango','Township'),
	(46,'Nyamira','Mwingi Central','North Mugirango','Itibo'),
	(46,'Nyamira','Mwingi Central','North Mugirango','Bomwagamo'),
	(46,'Nyamira','Mwingi Central','North Mugirango','Bokeira'),
	(46,'Nyamira','Mwingi Central','North Mugirango','Magwagwa'),
	(46,'Nyamira','Mwingi Central','North Mugirango','Ekerenyo'),
	(47,'Nairobi','Mwingi Central','Westlands','Kitisuru'),
	(47,'Nairobi','Mwingi Central','Westlands','Parklands/Highridge'),
	(47,'Nairobi','Mwingi Central','Westlands','Karura'),
	(47,'Nairobi','Mwingi Central','Westlands','Kangemi'),
	(47,'Nairobi','Mwingi Central','Westlands','Mountain View'),
	(47,'Nairobi','Mwingi Central','Dagoretti North','Kilimani'),
	(47,'Nairobi','Mwingi Central','Dagoretti North','Kawangware'),
	(47,'Nairobi','Mwingi Central','Dagoretti North','Gatina'),
	(47,'Nairobi','Mwingi Central','Dagoretti North','Kileleshwa'),
	(47,'Nairobi','Mwingi Central','Dagoretti North','Kabiro'),
	(47,'Nairobi','Mwingi Central','Dagoretti South','Mutu-Ini'),
	(47,'Nairobi','Mwingi Central','Dagoretti South','Ngando'),
	(47,'Nairobi','Mwingi Central','Dagoretti South','Riruta'),
	(47,'Nairobi','Mwingi Central','Dagoretti South','Uthiru/Ruthimitu'),
	(47,'Nairobi','Mwingi Central','Dagoretti South','Waithaka'),
	(47,'Nairobi','Mwingi Central','Lang''ata','Karen'),
	(47,'Nairobi','Mwingi Central','Lang''ata','Nairobi West'),
	(47,'Nairobi','Mwingi Central','Lang''ata','Mugumu-Ini'),
	(47,'Nairobi','Mwingi Central','Lang''ata','South C'),
	(47,'Nairobi','Mwingi Central','Lang''ata','Nyayo Highrise'),
	(47,'Nairobi','Mwingi Central','Kibra','Woodley/Kenyatta Golf Course'),
	(47,'Nairobi','Mwingi Central','Kibra','Sarang''ombe'),
	(47,'Nairobi','Mwingi Central','Kibra','Makina'),
	(47,'Nairobi','Mwingi Central','Kibra','Lindi'),
	(47,'Nairobi','Mwingi Central','Kibra','Laini Saba'),
	(47,'Nairobi','Mwingi Central','Roysambu','Kahawa West'),
	(47,'Nairobi','Mwingi Central','Roysambu','Roysambu'),
	(47,'Nairobi','Mwingi Central','Roysambu','Githurai'),
	(47,'Nairobi','Mwingi Central','Roysambu','Kahawa'),
	(47,'Nairobi','Mwingi Central','Roysambu','Zimmerman'),
	(47,'Nairobi','Mwingi Central','Kasarani','Kasarani'),
	(47,'Nairobi','Mwingi Central','Kasarani','Njiru'),
	(47,'Nairobi','Mwingi Central','Kasarani','Clay City'),
	(47,'Nairobi','Mwingi Central','Kasarani','Mwiki'),
	(47,'Nairobi','Mwingi Central','Kasarani','Ruai'),
	(47,'Nairobi','Mwingi Central','Ruaraka','Utalii'),
	(47,'Nairobi','Mwingi Central','Ruaraka','Korogocho'),
	(47,'Nairobi','Mwingi Central','Ruaraka','Lucky Summer'),
	(47,'Nairobi','Mwingi Central','Ruaraka','Mathare North'),
	(47,'Nairobi','Mwingi Central','Ruaraka','Baba Dogo'),
	(47,'Nairobi','Mwingi Central','Embakasi South','Kwa Njenga'),
	(47,'Nairobi','Mwingi Central','Embakasi South','Imara Daima'),
	(47,'Nairobi','Mwingi Central','Embakasi South','Kware'),
	(47,'Nairobi','Mwingi Central','Embakasi South','Kwa Reuben'),
	(47,'Nairobi','Mwingi Central','Embakasi South','Pipeline'),
	(47,'Nairobi','Mwingi Central','Embakasi North','Dandora Area I'),
	(47,'Nairobi','Mwingi Central','Embakasi North','Dandora Area II'),
	(47,'Nairobi','Mwingi Central','Embakasi North','Dandora Area III'),
	(47,'Nairobi','Mwingi Central','Embakasi North','Dandora Area IV'),
	(47,'Nairobi','Mwingi Central','Embakasi North','Kariobangi North'),
	(47,'Nairobi','Mwingi Central','Embakasi Central','Kayole North'),
	(47,'Nairobi','Mwingi Central','Embakasi Central','Kayole Central'),
	(47,'Nairobi','Mwingi Central','Embakasi Central','Kariobangi South'),
	(47,'Nairobi','Mwingi Central','Embakasi Central','Komarock'),
	(47,'Nairobi','Mwingi Central','Embakasi Central','Matopeni / Spring Valley'),
	(47,'Nairobi','Mwingi Central','Embakasi East','Utawala'),
	(47,'Nairobi','Mwingi Central','Embakasi East','Upper Savanna'),
	(47,'Nairobi','Mwingi Central','Embakasi East','Lower Savanna'),
	(47,'Nairobi','Mwingi Central','Embakasi East','Embakasi'),
	(47,'Nairobi','Mwingi Central','Embakasi East','Mihango'),
	(47,'Nairobi','Mwingi Central','Embakasi West','Umoja 1'),
	(47,'Nairobi','Mwingi Central','Embakasi West','Umoja 2'),
	(47,'Nairobi','Mwingi Central','Embakasi West','Mowlem '),
	(47,'Nairobi','Mwingi Central','Embakasi West','Kariobangi south'),
	(47,'Nairobi','Mwingi Central','Embakasi West','Maringo/ Hamza'),
	(47,'Nairobi','Mwingi Central','Makadara','Viwandani'),
	(47,'Nairobi','Mwingi Central','Makadara','Harambee'),
	(47,'Nairobi','Mwingi Central','Makadara','Makongeni'),
	(47,'Nairobi','Mwingi Central','Makadara','Pumwani'),
	(47,'Nairobi','Mwingi Central','Makadara','Eastleigh North'),
	(47,'Nairobi','Mwingi Central','Kamukunji','Eastleigh South'),
	(47,'Nairobi','Mwingi Central','Kamukunji','Nairobi Central'),
	(47,'Nairobi','Mwingi Central','Kamukunji','Airbase'),
	(47,'Nairobi','Mwingi Central','Kamukunji','California'),
	(47,'Nairobi','Mwingi Central','Kamukunji','Mgara'),
	(47,'Nairobi','Mwingi Central','Starehe','Nairobi South'),
	(47,'Nairobi','Mwingi Central','Starehe','Hospital'),
	(47,'Nairobi','Mwingi Central','Starehe','Ngara'),
	(47,'Nairobi','Mwingi Central','Starehe','Pangani'),
	(47,'Nairobi','Mwingi Central','Starehe','Landimawe'),
	(47,'Nairobi','Mwingi Central','Starehe','Ziwani / Kariokor'),
	(47,'Nairobi','Mwingi Central','Mathare','Mlango Kubwa'),
	(47,'Nairobi','Mwingi Central','Mathare','Kiamaiko'),
	(47,'Nairobi','Mwingi Central','Mathare','Ngei'),
	(47,'Nairobi','Mwingi Central','Mathare','Huruma'),
	(47,'Nairobi','Mwingi Central','Mathare','Mabatini');
