CREATE TABLE IF NOT EXISTS county (
    `county_code` INT,
    `county_name` VARCHAR(15) CHARACTER SET utf8,
    `constituencies_constituency_name` VARCHAR(19) CHARACTER SET utf8,
    `constituencies_wards` VARCHAR(25) CHARACTER SET utf8,
	PRIMARY KEY (`county_code`)

);
INSERT INTO county VALUES
 (1,'Mombasa','Changamwe','Port Reitz'),
	(1,'Mombasa','Changamwe','Kipevu'),
	(1,'Mombasa','Changamwe','Airport'),
	(1,'Mombasa','Changamwe','Miritini'),
	(1,'Mombasa','Changamwe','Chaani'),
	(1,'Mombasa','Jomvu','Jomvu Kuu'),
	(1,'Mombasa','Jomvu','Magongo'),
	(1,'Mombasa','Jomvu','Mikindani'),
	(1,'Mombasa','Kisauni','Mjambere'),
	(1,'Mombasa','Kisauni','Junda'),
	(1,'Mombasa','Kisauni','Bamburi'),
	(1,'Mombasa','Kisauni','Mwakirunge'),
	(1,'Mombasa','Kisauni','Mtopanga'),
	(1,'Mombasa','Kisauni','Magogoni'),
	(1,'Mombasa','Kisauni','Shanzu'),
	(1,'Mombasa','Likoni','Mtongwe'),
	(1,'Mombasa','Likoni','Shika adabu'),
	(1,'Mombasa','Likoni','Bofu'),
	(1,'Mombasa','Likoni','Likoni'),
	(1,'Mombasa','Likoni','Timbwani'),
	(1,'Mombasa','Mvita','Mji wa Kale/Makadara'),
	(1,'Mombasa','Mvita','Tudor'),
	(1,'Mombasa','Mvita','Tononoka'),
	(1,'Mombasa','Mvita','Ganjoni/Shimanzi'),
	(1,'Mombasa','Mvita','Majengo'),
	(1,'Mombasa','Nyali','Frere Town'),
	(1,'Mombasa','Nyali','Ziwa la Ng''ombe'),
	(1,'Mombasa','Nyali','Mkomani'),
	(1,'Mombasa','Nyali','Kongowea'),
	(1,'Mombasa','Nyali','Ziwani/Kadzandani'),
	(2,'Kwale','Kinango','Ndavaya'),
	(2,'Kwale','Kinango','Puma'),
	(2,'Kwale','Kinango','Kinango'),
	(2,'Kwale','Kinango','Chengoni/Samburu'),
	(2,'Kwale','Kinango','Mackinon Road'),
	(2,'Kwale','Kinango','Mwavumbo'),
	(2,'Kwale','Kinango','Kasemeni'),
	(2,'Kwale','Lunga Lunga','Pongwe/Kikoneni'),
	(2,'Kwale','Lunga Lunga','Dzombo'),
	(2,'Kwale','Lunga Lunga','Vanga'),
	(2,'Kwale','Lunga Lunga',' Mwereni'),
	(2,'Kwale','Msambweni','Gombato Bongwe'),
	(2,'Kwale','Msambweni',' Ukunda'),
	(2,'Kwale','Msambweni','Kinondo'),
	(2,'Kwale','Msambweni','Ramisi'),
	(2,'Kwale','Matuga','  Tsimba Golini'),
	(2,'Kwale','Matuga','Waa'),
	(2,'Kwale','Matuga','Tiwi'),
	(2,'Kwale','Matuga','Kubo South'),
	(2,'Kwale','Matuga','Mkongani'),
	(3,'Kilifi','Matuga','Tezo'),
	(3,'Kilifi','Matuga','Sokoni'),
	(3,'Kilifi','Matuga','Kibarani'),
	(3,'Kilifi','Matuga','Dabaso'),
	(3,'Kilifi','Matuga','Matsangoni'),
	(3,'Kilifi','Matuga','Watamu'),
	(3,'Kilifi','Matuga','Mnarani'),
	(3,'Kilifi','Matuga','Junju'),
	(3,'Kilifi','Matuga','Mwarakaya'),
	(3,'Kilifi','Matuga','Shimo la Tewa'),
	(3,'Kilifi','Matuga','Chasimba'),
	(3,'Kilifi','Matuga','Mtepeni'),
	(3,'Kilifi','Matuga','Mariakani'),
	(3,'Kilifi','Matuga','Kayafungo'),
	(3,'Kilifi','Matuga','Kaloleni'),
	(3,'Kilifi','Matuga','Mwanamwinga'),
	(3,'Kilifi','Matuga','Dungicha'),
	(3,'Kilifi','Matuga','Bamba'),
	(3,'Kilifi','Matuga','Jaribuni'),
	(3,'Kilifi','Matuga','Sokoke'),
	(3,'Kilifi','Matuga','Maarafa'),
	(3,'Kilifi','Matuga','Magarini'),
	(3,'Kilifi','Matuga','Gongoni'),
	(3,'Kilifi','Matuga','Adu'),
	(3,'Kilifi','Matuga','Garashi'),
	(3,'Kilifi','Matuga','Sabaki'),
	(3,'Kilifi','Matuga','Mwawesa'),
	(3,'Kilifi','Matuga','Ruruma'),
	(3,'Kilifi','Matuga','Jibana'),
	(3,'Kilifi','Matuga','Rabai/Kisurutuni'),
	(3,'Kilifi','Matuga','Jilore'),
	(3,'Kilifi','Matuga','Kakuyuni'),
	(3,'Kilifi','Matuga','Ganda'),
	(3,'Kilifi','Matuga','Malindi Town'),
	(3,'Kilifi','Matuga','Shella'),
	(4,'Tana River','Garsen','Garsen Central'),
	(4,'Tana River','Garsen','Garsen East'),
	(4,'Tana River','Garsen','Garsen North'),
	(4,'Tana River','Garsen','Garsen South'),
	(4,'Tana River','Garsen','Kipini East'),
	(4,'Tana River','Garsen','Kipini West'),
	(4,'Tana River','Galole','Kinakomba'),
	(4,'Tana River','Galole','Mikinduni'),
	(4,'Tana River','Galole','Chewani'),
	(4,'Tana River','Galole','Wayu'),
	(4,'Tana River','Bura','Chewele'),
	(4,'Tana River','Bura','Hirimani'),
	(4,'Tana River','Bura','Bangale'),
	(4,'Tana River','Bura','Madogo'),
	(4,'Tana River','Bura','Sala'),
	(5,'Lamu','Lamu East','Faza'),
	(5,'Lamu','Lamu East','Kiunga'),
	(5,'Lamu','Lamu East','Basuba'),
	(5,'Lamu','Lamu West','Shella'),
	(5,'Lamu','Lamu West','Mkomani'),
	(5,'Lamu','Lamu West','Hindi'),
	(5,'Lamu','Lamu West','Mkunumbi'),
	(5,'Lamu','Lamu West','Hongwe'),
	(5,'Lamu','Lamu West','Witu'),
	(5,'Lamu','Lamu West','Bahari'),
	(6,'Taita-Taveta','Taveta','Chala'),
	(6,'Taita-Taveta','Taveta','Mahoo'),
	(6,'Taita-Taveta','Taveta','Bomani'),
	(6,'Taita-Taveta','Taveta','Mboghoni'),
	(6,'Taita-Taveta','Taveta','Mata'),
	(6,'Taita-Taveta','Wundanyi','Wundanyi/Mbale'),
	(6,'Taita-Taveta','Wundanyi','Werugha'),
	(6,'Taita-Taveta','Wundanyi','Wumingu/Kishushe'),
	(6,'Taita-Taveta','Wundanyi','Mwanda/Mgange'),
	(6,'Taita-Taveta','Mwatate','Ronge'),
	(6,'Taita-Taveta','Mwatate','Mwatate'),
	(6,'Taita-Taveta','Mwatate','Bura'),
	(6,'Taita-Taveta','Mwatate','Chawia'),
	(6,'Taita-Taveta','Mwatate','Wusi/Kishamba'),
	(6,'Taita-Taveta','Voi','Mbololo'),
	(6,'Taita-Taveta','Voi','Kaloleni'),
	(6,'Taita-Taveta','Voi','Sagala'),
	(6,'Taita-Taveta','Voi','Marungu'),
	(6,'Taita-Taveta','Voi','Kaigau'),
	(6,'Taita-Taveta','Voi','Ngolia'),
	(7,'Garissa','Dujis','Waberi'),
	(7,'Garissa','Dujis','Galbet'),
	(7,'Garissa','Dujis','Township'),
	(7,'Garissa','Dujis','Iftin'),
	(7,'Garissa','Balambala','Balambala'),
	(7,'Garissa','Balambala','Danyere'),
	(7,'Garissa','Balambala','Jarajara'),
	(7,'Garissa','Balambala','Saka'),
	(7,'Garissa','Balambala','Sankuri'),
	(7,'Garissa','Dadaab','Dertu'),
	(7,'Garissa','Dadaab','Dadaab'),
	(7,'Garissa','Dadaab','Labasigale'),
	(7,'Garissa','Dadaab','Damajale'),
	(7,'Garissa','Dadaab','Liboi'),
	(7,'Garissa','Dadaab','Abakaile'),
	(7,'Garissa','Fafi','Bura'),
	(7,'Garissa','Fafi','Dekaharia'),
	(7,'Garissa','Fafi','Jarajila'),
	(7,'Garissa','Fafi','Fafi'),
	(7,'Garissa','Fafi','Nanighi'),
	(7,'Garissa','Ijara','Hulugho'),
	(7,'Garissa','Ijara','Sangailu'),
	(7,'Garissa','Ijara','Ijara'),
	(7,'Garissa','Ijara','Masalani'),
	(7,'Garissa','Lagdera','Modogashe'),
	(7,'Garissa','Lagdera','Bename'),
	(7,'Garissa','Lagdera','Goreale'),
	(7,'Garissa','Lagdera','Maalamin'),
	(7,'Garissa','Lagdera','Sabena'),
	(7,'Garissa','Lagdera','Baraki'),
	(8,'Wajir','Wajir East','Wagbri'),
	(8,'Wajir','Wajir East','Township'),
	(8,'Wajir','Wajir East','Barwago'),
	(8,'Wajir','Wajir East','Khorof/Harar'),
	(8,'Wajir','Wajir North','Gurar'),
	(8,'Wajir','Wajir North','Bute'),
	(8,'Wajir','Wajir North','Korondile'),
	(8,'Wajir','Wajir North','Malkagufu'),
	(8,'Wajir','Wajir North','Batalu'),
	(8,'Wajir','Wajir North','Danaba'),
	(8,'Wajir','Wajir North','Godoma'),
	(8,'Wajir','Wajir South','Benane'),
	(8,'Wajir','Wajir South','Burder'),
	(8,'Wajir','Wajir South','Dadaja Bulla'),
	(8,'Wajir','Wajir South','Habaswein'),
	(8,'Wajir','Wajir South','Lagboghol South'),
	(8,'Wajir','Wajir South','Ibrahim Ure'),
	(8,'Wajir','Wajir West','Arbajahan'),
	(8,'Wajir','Wajir West','Hadado/Athibohol'),
	(8,'Wajir','Wajir West','Ademasajide'),
	(8,'Wajir','Wajir West','Ganyure'),
	(8,'Wajir','Wajir West','Wagalla'),
	(8,'Wajir','Tarbaj','Elben'),
	(8,'Wajir','Tarbaj','Sarman'),
	(8,'Wajir','Tarbaj','Tarbaj'),
	(8,'Wajir','Tarbaj','Wargadud'),
	(8,'Wajir','Eldas','Eldas'),
	(8,'Wajir','Eldas','Della'),
	(8,'Wajir','Eldas','Lakoley South/Basir'),
	(8,'Wajir','Eldas','Elnur/Tula Tula'),
	(9,'Mandera','Moyale','Butiye'),
	(9,'Mandera','Moyale','Sololo'),
	(9,'Mandera','Moyale','Heillu/Manyatta'),
	(9,'Mandera','Moyale','Golbo'),
	(9,'Mandera','Moyale','Moyale Township'),
	(9,'Mandera','Moyale','Uran'),
	(9,'Mandera','Moyale','Obbu'),
	(9,'Mandera','North Horr','Dukana'),
	(9,'Mandera','North Horr','Maikona'),
	(9,'Mandera','North Horr','Turbi'),
	(9,'Mandera','North Horr','North Horr'),
	(9,'Mandera','North Horr','Illeret'),
	(9,'Mandera','Laisamis','Loiyangalani'),
	(9,'Mandera','Laisamis','Kargi/South Horr'),
	(9,'Mandera','Laisamis','Korr/Ngurunit'),
	(9,'Mandera','Laisamis','Logo Logo'),
	(9,'Mandera','Laisamis','Laisamis'),
	(9,'Mandera','Saku','Sagate/Jaldesa'),
	(9,'Mandera','Saku','Karare'),
	(9,'Mandera','Saku','Marsabit Central'),
	(10,'Marsabit','Laisamis','  Loiyangalani'),
	(10,'Marsabit','Laisamis','Kargi/South Horr'),
	(10,'Marsabit','Laisamis','Korr/Ngurunit'),
	(10,'Marsabit','Laisamis','Logo Logo'),
	(10,'Marsabit','Laisamis','Laisamis'),
	(10,'Marsabit','North Horr','  Dukana'),
	(10,'Marsabit','North Horr','Maikona'),
	(10,'Marsabit','North Horr','Turbi'),
	(10,'Marsabit','North Horr','North Horr'),
	(10,'Marsabit','North Horr',' Illeret'),
	(10,'Marsabit','Saku','Sagate/Jaldesa'),
	(10,'Marsabit','Saku','Karare'),
	(10,'Marsabit','Saku','Marsabit Central'),
	(10,'Marsabit','Moyale','Butiye'),
	(10,'Marsabit','Moyale','Sololo'),
	(10,'Marsabit','Moyale','Heillu/Manyatta'),
	(10,'Marsabit','Moyale','Golbo'),
	(10,'Marsabit','Moyale','Moyale Township'),
	(10,'Marsabit','Moyale','Uran'),
	(10,'Marsabit','Moyale','Obbu'),
	(11,'Isiolo','Isiolo North','Wabera'),
	(11,'Isiolo','Isiolo North','Bulla Pesa'),
	(11,'Isiolo','Isiolo North','Chari'),
	(11,'Isiolo','Isiolo North','Cherab'),
	(11,'Isiolo','Isiolo North','Ngare Mara'),
	(11,'Isiolo','Isiolo North','Burat'),
	(11,'Isiolo','Isiolo North','Oldo/Nyiro'),
	(11,'Isiolo','Isiolo South','Garba Tulla'),
	(11,'Isiolo','Isiolo South','Kina'),
	(11,'Isiolo','Isiolo South','Sericho'),
	(12,'Meru','Buuri','Timau'),
	(12,'Meru','Buuri','Kisima'),
	(12,'Meru','Buuri','Kiirua/Naari'),
	(12,'Meru','Buuri','Ruiri/Rwarera'),
	(12,'Meru','Central Imenti','Mwanganthia'),
	(12,'Meru','Central Imenti','Abothuguchi Central'),
	(12,'Meru','Central Imenti','Abothuguchi West'),
	(12,'Meru','Central Imenti','Kiagu'),
	(12,'Meru','Central Imenti','Kibirichia'),
	(12,'Meru','Igembe Central','Akirang''ondu');
INSERT INTO county VALUES (12,'Meru','Igembe Central','Athiru'),
	(12,'Meru','Igembe Central','Ruujine'),
	(12,'Meru','Igembe Central','Igembe East Njia'),
	(12,'Meru','Igembe Central','Kangeta'),
	(12,'Meru','Igembe South','Maua'),
	(12,'Meru','Igembe South','Kegoi/Antubochiu'),
	(12,'Meru','Igembe South','Athiru'),
	(12,'Meru','Igembe South','Gaiti'),
	(12,'Meru','Igembe South','Akachiu'),
	(12,'Meru','Igembe South','Kanuni'),
	(12,'Meru','Igembe North','Antuambui'),
	(12,'Meru','Igembe North','Ntunene'),
	(12,'Meru','Igembe North','Antubetwe Kiongo'),
	(12,'Meru','Igembe North','Naathui'),
	(12,'Meru','Igembe North','Amwathi'),
	(12,'Meru','Tigania West','Athwana'),
	(12,'Meru','Tigania West','Akithi'),
	(12,'Meru','Tigania West','Kianjai'),
	(12,'Meru','Tigania West','Nkomo'),
	(12,'Meru','Tigania West','Mbeu'),
	(12,'Meru','Tigania East','Thangatha'),
	(12,'Meru','Tigania East','Mikinduri'),
	(12,'Meru','Tigania East','Kiguchwa'),
	(12,'Meru','Tigania East','Mithara'),
	(12,'Meru','Tigania East','Karama'),
	(12,'Meru','Imenti North','Municipality'),
	(12,'Meru','Imenti North','Ntima East'),
	(12,'Meru','Imenti North','Ntima West'),
	(12,'Meru','Imenti North','Nyaki West'),
	(12,'Meru','Imenti North','Nyaki East'),
	(12,'Meru','Imenti South','Mitunguu'),
	(12,'Meru','Imenti South','Igoji East'),
	(12,'Meru','Imenti South','Igoji West'),
	(12,'Meru','Imenti South','Abogeta East'),
	(12,'Meru','Imenti South','Abogeta West'),
	(12,'Meru','Imenti South','Nkuene'),
	(13,'Tharaka Nithi','Tharaka ','Gatunga'),
	(13,'Tharaka Nithi','Tharaka ','Mukothima'),
	(13,'Tharaka Nithi','Tharaka ','Nkondi'),
	(13,'Tharaka Nithi','Tharaka ','Chiakariga'),
	(13,'Tharaka Nithi','Tharaka ','Marimanti'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Mariani'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Karingani'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Magumoni'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Mugwe'),
	(13,'Tharaka Nithi','Chuka/Igambang’ombe','Igambang''ombe'),
	(13,'Tharaka Nithi','Maara','Mitheru'),
	(13,'Tharaka Nithi','Maara','Muthambi'),
	(13,'Tharaka Nithi','Maara','Mwimbi'),
	(13,'Tharaka Nithi','Maara','Ganga'),
	(13,'Tharaka Nithi','Maara','Chogoria'),
	(14,'Embu','Manyatta','Ruguru/Ngandori'),
	(14,'Embu','Manyatta','Kithimu'),
	(14,'Embu','Manyatta','Nginda'),
	(14,'Embu','Manyatta','Mbeti North'),
	(14,'Embu','Manyatta','Kirimari'),
	(14,'Embu','Manyatta','Gaturi South'),
	(14,'Embu','Runyenjes','Gaturi North'),
	(14,'Embu','Runyenjes','Kagaari South'),
	(14,'Embu','Runyenjes','Kagaari North'),
	(14,'Embu','Runyenjes','Central Ward'),
	(14,'Embu','Runyenjes','Kyeni North'),
	(14,'Embu','Runyenjes','Kyeni South'),
	(14,'Embu','Mbeere North','Nthawa'),
	(14,'Embu','Mbeere North','Muminji'),
	(14,'Embu','Mbeere North','Evurore'),
	(14,'Embu','Mbeere South','Mwea'),
	(14,'Embu','Mbeere South','Amakim'),
	(14,'Embu','Mbeere South','Mbeti South'),
	(14,'Embu','Mbeere South','Mavuria'),
	(14,'Embu','Mbeere South','Kiambere'),
	(15,'Kitui','Kitui West','Mutonguni'),
	(15,'Kitui','Kitui West','Kauwi'),
	(15,'Kitui','Kitui West','Matinyani'),
	(15,'Kitui','Kitui West','Kwa Mutonga/Kithum Ula'),
	(15,'Kitui','Kitui Central','Miambani'),
	(15,'Kitui','Kitui Central','Township Kyangwithya West'),
	(15,'Kitui','Kitui Central','Mulango'),
	(15,'Kitui','Kitui Central','Kyangwithya East'),
	(15,'Kitui','Kitui Rural','Kisasi'),
	(15,'Kitui','Kitui Rural','Mbitini'),
	(15,'Kitui','Kitui Rural','Kwavonza/Yatta'),
	(15,'Kitui','Kitui Rural','Kanyangi'),
	(15,'Kitui','Kitui South','Ikana/Kyantune'),
	(15,'Kitui','Kitui South','Mutomo'),
	(15,'Kitui','Kitui South','Mutha'),
	(15,'Kitui','Kitui South','Ikutha'),
	(15,'Kitui','Kitui South','Kanziko'),
	(15,'Kitui','Kitui South','Athi'),
	(15,'Kitui','Kitui East','Zombe/Mwitika'),
	(15,'Kitui','Kitui East','Nzambani'),
	(15,'Kitui','Kitui East','Chuluni'),
	(15,'Kitui','Kitui East','Voo/Kyamatu'),
	(15,'Kitui','Kitui East','Endau/Malalani'),
	(15,'Kitui','Kitui East','Mutito/Kaliku'),
	(15,'Kitui','Mwingi North','Ngomeni'),
	(15,'Kitui','Mwingi North','Kyuso'),
	(15,'Kitui','Mwingi North','Mumoni'),
	(15,'Kitui','Mwingi North','Tseikuru'),
	(15,'Kitui','Mwingi North','Tharaka'),
	(15,'Kitui','Mwingi West','Kyome/Thaana'),
	(15,'Kitui','Mwingi West','Nguutani'),
	(15,'Kitui','Mwingi West','Migwani'),
	(15,'Kitui','Mwingi West','Kiomo/Kyethani'),
	(15,'Kitui','mwingi central','Central'),
	(15,'Kitui','mwingi central','Kivou'),
	(15,'Kitui','mwingi central','Nguni'),
	(15,'Kitui','mwingi central','Mui'),
	(15,'Kitui','mwingi central','Waita'),
	(16,'Machakos','Masinga','Kivaa'),
	(16,'Machakos','Masinga','Masinga'),
	(16,'Machakos','Masinga','Central'),
	(16,'Machakos','Masinga','Ekalakala'),
	(16,'Machakos','Masinga','Muthesya'),
	(16,'Machakos','Masinga','Ndithini'),
	(16,'Machakos','Yatta','Ndalani'),
	(16,'Machakos','Yatta','Matuu'),
	(16,'Machakos','Yatta','Kithimani'),
	(16,'Machakos','Yatta','Ikomba'),
	(16,'Machakos','Yatta','Katangi'),
	(16,'Machakos','Matungulu','Tala'),
	(16,'Machakos','Matungulu','Matungulu North'),
	(16,'Machakos','Matungulu','Matungulu East'),
	(16,'Machakos','Matungulu','Matungulu West'),
	(16,'Machakos','Matungulu','Kyeleni'),
	(16,'Machakos','Kangundo','Kangundo North'),
	(16,'Machakos','Kangundo','Kangundo Central'),
	(16,'Machakos','Kangundo','Kangundo East'),
	(16,'Machakos','Kangundo','Kangundo West'),
	(16,'Machakos','Mwala','Mbiuni'),
	(16,'Machakos','Mwala','Makutano/Mwala'),
	(16,'Machakos','Mwala','Masii'),
	(16,'Machakos','Mwala','Muthetheni'),
	(16,'Machakos','Mwala','Wamunyu'),
	(16,'Machakos','Mwala','Kibauni'),
	(16,'Machakos','Kathiani','Mitaboni'),
	(16,'Machakos','Kathiani','Kathiani Central'),
	(16,'Machakos','Kathiani','Upper Kaewa/Iveti'),
	(16,'Machakos','Kathiani','Lower Kaewa/Kaani'),
	(16,'Machakos','Machakos Town','Kalama'),
	(16,'Machakos','Machakos Town','Mua'),
	(16,'Machakos','Machakos Town','Mutitini'),
	(16,'Machakos','Machakos Town','Machakos Central'),
	(16,'Machakos','Machakos Town','Mumbuni North'),
	(16,'Machakos','Machakos Town','Muvuti/Kiima-Kimwe'),
	(16,'Machakos','Machakos Town','Kola'),
	(16,'Machakos','Mavoko','Athi River'),
	(16,'Machakos','Mavoko','Kinanie'),
	(16,'Machakos','Mavoko','Muthwani'),
	(16,'Machakos','Mavoko','Syokimau/Mulolongo'),
	(16,'Machakos','Mbooni','Tulimani'),
	(16,'Machakos','Mbooni','Mbooni'),
	(16,'Machakos','Mbooni','Kithungo/Kitundu'),
	(16,'Machakos','Mbooni','Kiteta/Kisau'),
	(16,'Machakos','Mbooni','Waia-Kako'),
	(16,'Machakos','Mbooni','Kalawa'),
	(16,'Machakos','Kaiti','Ukia'),
	(16,'Machakos','Kaiti','Kee'),
	(16,'Machakos','Kaiti','Kilungu'),
	(16,'Machakos','Kaiti','Ilima'),
	(16,'Machakos','Makueni','Wote'),
	(16,'Machakos','Makueni','Muvau/Kikuumini'),
	(16,'Machakos','Makueni','Mavindini'),
	(16,'Machakos','Makueni','Kitise/Kithuki'),
	(16,'Machakos','Makueni','Kathonzweni'),
	(16,'Machakos','Makueni','Nzau/Kilili/Kalamba'),
	(16,'Machakos','Makueni','Mbitini'),
	(16,'Machakos','Kilome','Kasikeu'),
	(16,'Machakos','Kilome','Mukaa'),
	(16,'Machakos','Kilome','Kiima Kiu/Kalanzoni'),
	(16,'Machakos','Kibwezi East','Masongaleni'),
	(16,'Machakos','Kibwezi East','Mtito Andei'),
	(16,'Machakos','Kibwezi East','Thange'),
	(16,'Machakos','Kibwezi East','Ivingoni/Nzambani'),
	(16,'Machakos','Kibwezi West','Makindu'),
	(16,'Machakos','Kibwezi West','Nguumo'),
	(16,'Machakos','Kibwezi West','Kikumbulyu North'),
	(16,'Machakos','Kibwezi West','Kimumbulyu South'),
	(16,'Machakos','Kibwezi West','Nguu/Masumba'),
	(16,'Machakos','Kibwezi West','Emali/Mulala'),
	(18,'Nyandarua','Kinangop','Engineer'),
	(18,'Nyandarua','Kinangop','Gathara'),
	(18,'Nyandarua','Kinangop','North Kinangop'),
	(18,'Nyandarua','Kinangop','Murungaru'),
	(18,'Nyandarua','Kinangop','Njabini/Kiburu'),
	(18,'Nyandarua','Kinangop','Nyakio'),
	(18,'Nyandarua','Kinangop','Githabai'),
	(18,'Nyandarua','Kinangop','Magumu'),
	(18,'Nyandarua','Kipipiri','Wanjohi'),
	(18,'Nyandarua','Kipipiri','Kipipiri'),
	(18,'Nyandarua','Kipipiri','Geta'),
	(18,'Nyandarua','Kipipiri','Githioro'),
	(18,'Nyandarua','Ol Joro Orok','Gathanji'),
	(18,'Nyandarua','Ol Joro Orok','Gatima'),
	(18,'Nyandarua','Ol Joro Orok','Weru'),
	(18,'Nyandarua','Ol Joro Orok','Charagita'),
	(18,'Nyandarua','Ndaragwa','Leshau/Pondo'),
	(18,'Nyandarua','Ndaragwa','Kiriita'),
	(18,'Nyandarua','Ndaragwa','Central'),
	(18,'Nyandarua','Ndaragwa','Shamata'),
	(18,'Nyandarua','Ol Kalou','Karau'),
	(18,'Nyandarua','Ol Kalou','Kanjuiri Range'),
	(18,'Nyandarua','Ol Kalou','Mirangine'),
	(18,'Nyandarua','Ol Kalou','Kaimbaga'),
	(18,'Nyandarua','Ol Kalou','Rurii'),
	(19,'Nyeri','Mathira','Ruguru'),
	(19,'Nyeri','Mathira','Magutu'),
	(19,'Nyeri','Mathira','Iriani'),
	(19,'Nyeri','Mathira','Konyu'),
	(19,'Nyeri','Mathira','Kirimukuyu'),
	(19,'Nyeri','Mathira','Karatina Town'),
	(19,'Nyeri','Othaya','Mahiga'),
	(19,'Nyeri','Othaya','Iria-Ini'),
	(19,'Nyeri','Othaya','Chinga'),
	(19,'Nyeri','Othaya','Karima'),
	(19,'Nyeri','Tetu','Dedan Kimathi'),
	(19,'Nyeri','Tetu','Wamagana'),
	(19,'Nyeri','Tetu','Aguthi-Gaaki'),
	(19,'Nyeri','Mukurweini','Gikondi'),
	(19,'Nyeri','Mukurweini','Rugi'),
	(19,'Nyeri','Mukurweini','Mukurwe-Ini West'),
	(19,'Nyeri','Mukurweini','Mukurwe-Ini Central'),
	(19,'Nyeri','Tetu','Dedan Kimathi'),
	(19,'Nyeri','Tetu','Wamagana'),
	(19,'Nyeri','Tetu','Aguthi-Gaaki'),
	(19,'Nyeri','Nyeri Town','Kiganjo/Mathari'),
	(19,'Nyeri','Nyeri Town','Rware'),
	(19,'Nyeri','Nyeri Town','Gatitu/Muruguru'),
	(19,'Nyeri','Nyeri Town','Ruring’u'),
	(19,'Nyeri','Nyeri Town','Kamakwa/Mukaro'),
	(19,'Nyeri','Kieni','Mweiga'),
	(19,'Nyeri','Kieni','Naromoro Kiamthaga'),
	(19,'Nyeri','Kieni','Mwiyogo/Endara Sha'),
	(19,'Nyeri','Kieni','Mugunda'),
	(19,'Nyeri','Kieni','Gatarakwa'),
	(19,'Nyeri','Kieni','Thegu River'),
	(19,'Nyeri','Kieni','Kabaru'),
	(19,'Nyeri','Kieni','Gakawa'),
	(20,'Kirinyaga','Kirinyaga Central','Mutira'),
	(20,'Kirinyaga','Kirinyaga Central','Kanyekini'),
	(20,'Kirinyaga','Kirinyaga Central','Kerugoya'),
	(20,'Kirinyaga','Kirinyaga Central','Inoi'),
	(20,'Kirinyaga','Mwea','Mutithi'),
	(20,'Kirinyaga','Mwea','Kangai'),
	(20,'Kirinyaga','Mwea','Wamumu'),
	(20,'Kirinyaga','Mwea','Nyangati'),
	(20,'Kirinyaga','Mwea','Murindiko'),
	(20,'Kirinyaga','Mwea','Gathigiriri'),
	(20,'Kirinyaga','Mwea','Teberer'),
	(20,'Kirinyaga','Mwea','Thiba');
INSERT INTO county VALUES (20,'Kirinyaga','Gichugu','Kabare Baragwi'),
	(20,'Kirinyaga','Gichugu','Njukiini'),
	(20,'Kirinyaga','Gichugu','Ngariama'),
	(20,'Kirinyaga','Gichugu','Karumandi'),
	(20,'Kirinyaga','Ndia','Mukure'),
	(20,'Kirinyaga','Ndia','Kiine'),
	(20,'Kirinyaga','Ndia','Kariti'),
	(21,'Murang’a','Gatanga','Ithanga'),
	(21,'Murang’a','Gatanga','Kakuzi/Mitubiri'),
	(21,'Murang’a','Gatanga','Mugumo-Ini'),
	(21,'Murang’a','Gatanga','Kihumbu-Ini'),
	(21,'Murang’a','Gatanga','Gatanga'),
	(21,'Murang’a','Gatanga','Kariara'),
	(21,'Murang’a','Kandara','Ng’ararii'),
	(21,'Murang’a','Kandara','Muruka'),
	(21,'Murang’a','Kandara','Kangundu-Ini'),
	(21,'Murang’a','Kandara','Gaichanjiru'),
	(21,'Murang’a','Kandara','Ithiru'),
	(21,'Murang’a','Kandara','Ruchu'),
	(21,'Murang’a','Kigumo','Kahumbu'),
	(21,'Murang’a','Kigumo','Muthithi'),
	(21,'Murang’a','Kigumo','Kigumo'),
	(21,'Murang’a','Kigumo','Kangari'),
	(21,'Murang’a','Kigumo','Kinyona'),
	(21,'Murang’a','Mathioya','Gituhi'),
	(21,'Murang’a','Mathioya','Kiru'),
	(21,'Murang’a','Mathioya','Kamacharia'),
	(21,'Murang’a','Kiharu','Wangu'),
	(21,'Murang’a','Kiharu','Mugoiri'),
	(21,'Murang’a','Kiharu','Mbiri'),
	(21,'Murang’a','Kiharu','Township'),
	(21,'Murang’a','Kiharu','Murarandia'),
	(21,'Murang’a','Kiharu','Gaturi'),
	(21,'Murang’a','Kangema','Kanyenya-Ini'),
	(21,'Murang’a','Kangema','Muguru'),
	(21,'Murang’a','Kangema','Rwathia'),
	(21,'Murang’a','Maragwa','Kimorori/Wempa'),
	(21,'Murang’a','Maragwa','Makuyu'),
	(21,'Murang’a','Maragwa','Kambiti'),
	(21,'Murang’a','Maragwa','Kamahuha'),
	(21,'Murang’a','Maragwa','Ichagaki'),
	(21,'Murang’a','Maragwa','Nginda'),
	(22,'Kiambu','Gatundu North','Gituamba'),
	(22,'Kiambu','Gatundu North','Githobokoni'),
	(22,'Kiambu','Gatundu North','Chania'),
	(22,'Kiambu','Gatundu North','Mang’u'),
	(22,'Kiambu','Gatundu South','Kiamwangi'),
	(22,'Kiambu','Gatundu South','Kiganjo'),
	(22,'Kiambu','Gatundu South','Ndarugu'),
	(22,'Kiambu','Gatundu South','Ngenda'),
	(22,'Kiambu','Githunguri','Githunguri'),
	(22,'Kiambu','Githunguri','Githiga'),
	(22,'Kiambu','Githunguri','Ikinu'),
	(22,'Kiambu','Githunguri','Ngewa'),
	(22,'Kiambu','Githunguri','Komothai'),
	(22,'Kiambu','Juja','Murera'),
	(22,'Kiambu','Juja','Theta'),
	(22,'Kiambu','Juja','Juja'),
	(22,'Kiambu','Juja','Witeithie'),
	(22,'Kiambu','Juja','Kalimoni'),
	(22,'Kiambu','Kabete','Gitaru'),
	(22,'Kiambu','Kabete','Muguga'),
	(22,'Kiambu','Kabete','Nyathuna'),
	(22,'Kiambu','Kabete','Kabete'),
	(22,'Kiambu','Kabete','Uthiru'),
	(22,'Kiambu','Kiambaa','Cianda'),
	(22,'Kiambu','Kiambaa','Karuiri'),
	(22,'Kiambu','Kiambaa','Ndenderu'),
	(22,'Kiambu','Kiambaa','Muchatha'),
	(22,'Kiambu','Kiambaa','Kihara'),
	(22,'Kiambu','Kiambu','Ting’gang’a'),
	(22,'Kiambu','Kiambu','Ndumberi'),
	(22,'Kiambu','Kiambu','Riabai'),
	(22,'Kiambu','Kiambu','Township'),
	(22,'Kiambu','Limuru','Bibirioni'),
	(22,'Kiambu','Limuru','Limuru Central'),
	(22,'Kiambu','Limuru','Ndeiya'),
	(22,'Kiambu','Limuru','Limuru East'),
	(22,'Kiambu','Limuru','Ngecha Tigoni'),
	(22,'Kiambu','Kikuyu','Karai'),
	(22,'Kiambu','Kikuyu','Nachu'),
	(22,'Kiambu','Kikuyu','Sigona'),
	(22,'Kiambu','Kikuyu','Kikuyu'),
	(22,'Kiambu','Kikuyu','Kinoo'),
	(22,'Kiambu','Lari','Kijabe'),
	(22,'Kiambu','Lari','Nyanduma'),
	(22,'Kiambu','Lari','Kamburu'),
	(22,'Kiambu','Lari','Lari/Kirenga'),
	(22,'Kiambu','Ruiru','Gitothua'),
	(22,'Kiambu','Ruiru','Biashara'),
	(22,'Kiambu','Ruiru','Gatongora'),
	(22,'Kiambu','Ruiru','Kahawa Sukari'),
	(22,'Kiambu','Ruiru','Kahawa Wendani'),
	(22,'Kiambu','Ruiru','Kiuu'),
	(22,'Kiambu','Ruiru','Mwiki'),
	(22,'Kiambu','Ruiru','Mwihoko'),
	(22,'Kiambu','Thika Town','Township'),
	(22,'Kiambu','Thika Town','Kamenu'),
	(22,'Kiambu','Thika Town','Hospital'),
	(22,'Kiambu','Thika Town','Gatuanyaga'),
	(22,'Kiambu','Thika Town','Ngoliba'),
	(23,'Turkana','Turkana Central','Kerio Delta'),
	(23,'Turkana','Turkana Central','Kang’atotha'),
	(23,'Turkana','Turkana Central','Kalokol'),
	(23,'Turkana','Turkana Central','Lodwar Township'),
	(23,'Turkana','Turkana Central','Kanamkemer'),
	(23,'Turkana','Turkana East','Kapedo/Napeito'),
	(23,'Turkana','Turkana East','Katilia'),
	(23,'Turkana','Turkana East','Lokori/Kochodin'),
	(23,'Turkana','Turkana North','Kaeris'),
	(23,'Turkana','Turkana North','Lake zone'),
	(23,'Turkana','Turkana North','Lapur'),
	(23,'Turkana','Turkana North','Kaaleng/kaikor'),
	(23,'Turkana','Turkana North','Kibish'),
	(23,'Turkana','Turkana North','Nakalale'),
	(23,'Turkana','Turkana South','Kaputir'),
	(23,'Turkana','Turkana South','Katilu'),
	(23,'Turkana','Turkana South','Lobokat'),
	(23,'Turkana','Turkana South','Kalapata'),
	(23,'Turkana','Turkana South','Lokichar'),
	(23,'Turkana','Turkana West','Kakuma'),
	(23,'Turkana','Turkana West','Lopur'),
	(23,'Turkana','Turkana West','Letea'),
	(23,'Turkana','Turkana West','Songot'),
	(23,'Turkana','Turkana West','Kalobeyei'),
	(23,'Turkana','Turkana West','Lokichoggio'),
	(23,'Turkana','Turkana West','Nanaam'),
	(23,'Turkana','Loima','Kotaruk/Lobei'),
	(23,'Turkana','Loima','Turkwel'),
	(23,'Turkana','Loima','Loima'),
	(23,'Turkana','Loima','Lokiriama/Loren Gippi'),
	(24,'West pokot','Kapenguria','Riwo'),
	(24,'West pokot','Kapenguria','Kapenguria'),
	(24,'West pokot','Kapenguria','Mnagei'),
	(24,'West pokot','Kapenguria','Siyoi'),
	(24,'West pokot','Kapenguria','Endugh'),
	(24,'West pokot','Kapenguria','Sook'),
	(24,'West pokot','Sigor','Sekerr'),
	(24,'West pokot','Sigor','Masool'),
	(24,'West pokot','Sigor','Lomut'),
	(24,'West pokot','Sigor','Weiwei'),
	(24,'West pokot','Kacheliba','Suam'),
	(24,'West pokot','Kacheliba','Kodich'),
	(24,'West pokot','Kacheliba','Kasei'),
	(24,'West pokot','Kacheliba','Kapchok'),
	(24,'West pokot','Kacheliba','Kiwawa'),
	(24,'West pokot','Kacheliba','Alale'),
	(24,'West pokot','Pokot South','Chepareria'),
	(24,'West pokot','Pokot South','Batei'),
	(24,'West pokot','Pokot South','Lelan'),
	(24,'West pokot','Pokot South','Tapach'),
	(25,'Samburu','Samburu East','Waso'),
	(25,'Samburu','Samburu East','Wamba West'),
	(25,'Samburu','Samburu East','Wamba East'),
	(25,'Samburu','Samburu East','Wamba North'),
	(25,'Samburu','Samburu North','El-Barta'),
	(25,'Samburu','Samburu North','Nachola'),
	(25,'Samburu','Samburu North','Ndoto'),
	(25,'Samburu','Samburu North','Nyiro'),
	(25,'Samburu','Samburu North','Angata Nanyokie'),
	(25,'Samburu','Samburu North','Baawa'),
	(25,'Samburu','Samburu West','Lodokejek'),
	(25,'Samburu','Samburu West','Suguta Marmar'),
	(25,'Samburu','Samburu West','Maralal'),
	(25,'Samburu','Samburu West','Loosuk'),
	(25,'Samburu','Samburu West','Poro'),
	(26,'Trans-Nzoia','Cherang''any','Sinyerere'),
	(26,'Trans-Nzoia','Cherang''any','Makutano'),
	(26,'Trans-Nzoia','Cherang''any','Kaplamai'),
	(26,'Trans-Nzoia','Cherang''any','Motosiet'),
	(26,'Trans-Nzoia','Cherang''any','Cherangany/Suwerwa'),
	(26,'Trans-Nzoia','Cherang''any','Chepsiro/Kiptoror'),
	(26,'Trans-Nzoia','Cherang''any','Sitatunga'),
	(26,'Trans-Nzoia','Kwanza','Kapomboi'),
	(26,'Trans-Nzoia','Kwanza','Kwanza'),
	(26,'Trans-Nzoia','Kwanza','Keiyo'),
	(26,'Trans-Nzoia','Kwanza','Bidii'),
	(26,'Trans-Nzoia','Endebess','Chepchoina'),
	(26,'Trans-Nzoia','Endebess','Endebess'),
	(26,'Trans-Nzoia','Endebess','Matumbei'),
	(26,'Trans-Nzoia','Saboti','Kinyoro'),
	(26,'Trans-Nzoia','Saboti','Matisi'),
	(26,'Trans-Nzoia','Saboti','Tuwani'),
	(26,'Trans-Nzoia','Saboti','Saboti'),
	(26,'Trans-Nzoia','Saboti','Machewa'),
	(26,'Trans-Nzoia','Kiminini','Kiminini'),
	(26,'Trans-Nzoia','Kiminini','Waitaluk'),
	(26,'Trans-Nzoia','Kiminini','Sirende'),
	(26,'Trans-Nzoia','Kiminini','Hospital'),
	(26,'Trans-Nzoia','Kiminini','Sikhendu'),
	(26,'Trans-Nzoia','Kiminini','Nabiswa'),
	(27,'Uasin Gishu','Ainabkoi','Kapsoya'),
	(27,'Uasin Gishu','Ainabkoi','Kaptagat'),
	(27,'Uasin Gishu','Ainabkoi','Ainabkoi/Olare'),
	(27,'Uasin Gishu','Kapseret','Simat/Kapseret'),
	(27,'Uasin Gishu','Kapseret','Kipkenyo'),
	(27,'Uasin Gishu','Kapseret','Ngeria'),
	(27,'Uasin Gishu','Kapseret','Megun'),
	(27,'Uasin Gishu','Kapseret','Langas'),
	(27,'Uasin Gishu','Kesses','Racecourse'),
	(27,'Uasin Gishu','Kesses','Cheptiret/Kipchamo'),
	(27,'Uasin Gishu','Kesses','Tulwet/Chuiyat'),
	(27,'Uasin Gishu','Kesses','Tarakwa'),
	(27,'Uasin Gishu','Moiben','Tembelio'),
	(27,'Uasin Gishu','Moiben','Sergoit'),
	(27,'Uasin Gishu','Moiben','Karuna/Meibeki'),
	(27,'Uasin Gishu','Moiben','Moiben'),
	(27,'Uasin Gishu','Moiben','Kimumu'),
	(27,'Uasin Gishu','Soy','  Moi’s Bridge'),
	(27,'Uasin Gishu','Soy','Kapkures'),
	(27,'Uasin Gishu','Soy','Ziwa'),
	(27,'Uasin Gishu','Soy','Segero/Barsombe'),
	(27,'Uasin Gishu','Soy','Kipsom Ba'),
	(27,'Uasin Gishu','Soy','Soy'),
	(27,'Uasin Gishu','Soy','Kuinet/Kapsuswa'),
	(27,'Uasin Gishu','Turbo','  Ngenyilel'),
	(27,'Uasin Gishu','Turbo','Tapsagoi'),
	(27,'Uasin Gishu','Turbo','Kamagut'),
	(27,'Uasin Gishu','Turbo','Kiplombe'),
	(27,'Uasin Gishu','Turbo','Kapsaos'),
	(27,'Uasin Gishu','Turbo','Huruma'),
	(28,'Elgeyo-Marakwet','Keiyo North','Emsoo'),
	(28,'Elgeyo-Marakwet','Keiyo North','Kamariny'),
	(28,'Elgeyo-Marakwet','Keiyo North','Kapchemutwa'),
	(28,'Elgeyo-Marakwet','Keiyo North','Tambach'),
	(28,'Elgeyo-Marakwet','Keiyo South','Kaptarakwa'),
	(28,'Elgeyo-Marakwet','Keiyo South','Chepkorio'),
	(28,'Elgeyo-Marakwet','Keiyo South','Soy North'),
	(28,'Elgeyo-Marakwet','Keiyo South','Soy South'),
	(28,'Elgeyo-Marakwet','Keiyo South','Kabiemit'),
	(28,'Elgeyo-Marakwet','Keiyo South','Metkei'),
	(28,'Elgeyo-Marakwet','Marakwet East','Kapyego'),
	(28,'Elgeyo-Marakwet','Marakwet East','Sambirir'),
	(28,'Elgeyo-Marakwet','Marakwet East','Endo'),
	(28,'Elgeyo-Marakwet','Marakwet East','Embobut / Embulot'),
	(28,'Elgeyo-Marakwet','Marakwet West','Kapsowar'),
	(28,'Elgeyo-Marakwet','Marakwet West','Lelan'),
	(28,'Elgeyo-Marakwet','Marakwet West','Sengwer'),
	(28,'Elgeyo-Marakwet','Marakwet West','Cherang’any/Chebororwa'),
	(28,'Elgeyo-Marakwet','Marakwet West','Moiben/Kuserwo'),
	(28,'Elgeyo-Marakwet','Marakwet West','Arror'),
	(29,'Nandi','Aldai','Kabwareng'),
	(29,'Nandi','Aldai','Terik'),
	(29,'Nandi','Aldai','Kemeloi-Maraba'),
	(29,'Nandi','Aldai','Kobujoi'),
	(29,'Nandi','Aldai','Kaptumo-Kaboi'),
	(29,'Nandi','Aldai','Koyo-Ndurio'),
	(29,'Nandi','Chesumei','Chemundu/Kapng’etuny'),
	(29,'Nandi','Chesumei','Kosirai'),
	(29,'Nandi','Chesumei','Lelmokwo/Ngechek');
INSERT INTO county VALUES (29,'Nandi','Chesumei','Kaptel/Kamoiywo'),
	(29,'Nandi','Chesumei','Kiptuya'),
	(29,'Nandi','Emgwen','Chepkumia'),
	(29,'Nandi','Emgwen','Kapkangani'),
	(29,'Nandi','Emgwen','Kapsabet'),
	(29,'Nandi','Emgwen','Kilibwoni'),
	(29,'Nandi','Mosop','Chepterwai'),
	(29,'Nandi','Mosop','Kipkaren'),
	(29,'Nandi','Mosop','Kurgung/ Surungai'),
	(29,'Nandi','Mosop','Kabiyet'),
	(29,'Nandi','Mosop','Ndalat'),
	(29,'Nandi','Mosop','Kabisaga'),
	(29,'Nandi','Mosop','Sangalo/Kebulonik'),
	(29,'Nandi','Nandi Hills','Nandi Hills'),
	(29,'Nandi','Nandi Hills','Chepkunyuk'),
	(29,'Nandi','Nandi Hills','Ol’lessos'),
	(29,'Nandi','Nandi Hills','Kapchorua'),
	(29,'Nandi','Tinderet','Songhor/Soba'),
	(29,'Nandi','Tinderet','Tindiret'),
	(29,'Nandi','Tinderet','Chemelil/Chemase'),
	(29,'Nandi','Tinderet','Kapsimotwo'),
	(30,'Baringo','Baringo Central','Kabarnet'),
	(30,'Baringo','Baringo Central','Sacho'),
	(30,'Baringo','Baringo Central','Tenges'),
	(30,'Baringo','Baringo Central','Ewalel/Chapcha'),
	(30,'Baringo','Baringo Central','Kapropita'),
	(30,'Baringo','Baringo North','Barwessa'),
	(30,'Baringo','Baringo North','Kabartonjo'),
	(30,'Baringo','Baringo North','Saimo/Kipsaraman'),
	(30,'Baringo','Baringo North','Saimo/Soi'),
	(30,'Baringo','Baringo North','Bartabwa'),
	(30,'Baringo','Baringo South','Marigat'),
	(30,'Baringo','Baringo South','Ilchamus'),
	(30,'Baringo','Baringo South','Mochongoi'),
	(30,'Baringo','Baringo South','Mukutani'),
	(30,'Baringo','Eldama Ravine','Lembus'),
	(30,'Baringo','Eldama Ravine','Lembus Kwen'),
	(30,'Baringo','Eldama Ravine','Ravine'),
	(30,'Baringo','Eldama Ravine','Mumberes/Maji Mazuri'),
	(30,'Baringo','Eldama Ravine','Lembus /Pekerra'),
	(30,'Baringo','Mogotio','Mogotio'),
	(30,'Baringo','Mogotio','Emining'),
	(30,'Baringo','Mogotio','Kisanana'),
	(30,'Baringo','Tiaty','Tirioko'),
	(30,'Baringo','Tiaty','Kolowa'),
	(30,'Baringo','Tiaty','Ribkwo'),
	(30,'Baringo','Tiaty','Silale'),
	(30,'Baringo','Tiaty','Loiyamorock'),
	(30,'Baringo','Tiaty','Tangulbei/Korossi'),
	(30,'Baringo','Tiaty','Churo/Amaya'),
	(31,'Laikipia','Laikipia North','Sosian'),
	(31,'Laikipia','Laikipia North','Segera'),
	(31,'Laikipia','Laikipia North','Mugogodo West'),
	(31,'Laikipia','Laikipia North','Mugogodo East'),
	(31,'Laikipia','Laikipia East','Ngobit'),
	(31,'Laikipia','Laikipia East','Tigithi'),
	(31,'Laikipia','Laikipia East','Thingithu'),
	(31,'Laikipia','Laikipia East','Nanyuki'),
	(31,'Laikipia','Laikipia East',' Umande'),
	(31,'Laikipia','Laikipia West','Ol-Moran'),
	(31,'Laikipia','Laikipia West','Rumuruti'),
	(31,'Laikipia','Laikipia West','Township '),
	(31,'Laikipia','Laikipia West','Githiga'),
	(31,'Laikipia','Laikipia West','Marmanet'),
	(31,'Laikipia','Laikipia West','Igwamiti Salama'),
	(32,'Nakuru','Nakuru Town East','Biashara'),
	(32,'Nakuru','Nakuru Town East','Kivumbini'),
	(32,'Nakuru','Nakuru Town East','Flamingo'),
	(32,'Nakuru','Nakuru Town East','Menengai'),
	(32,'Nakuru','Nakuru Town East','Nakuru East'),
	(32,'Nakuru','Nakuru Town West','Barut'),
	(32,'Nakuru','Nakuru Town West','London'),
	(32,'Nakuru','Nakuru Town West','Kaptembwo'),
	(32,'Nakuru','Nakuru Town West','Kapkures'),
	(32,'Nakuru','Nakuru Town West','Rhoda'),
	(32,'Nakuru','Nakuru Town West','Shaabab'),
	(32,'Nakuru','Njoro','Mau Narok'),
	(32,'Nakuru','Njoro','Mauche'),
	(32,'Nakuru','Njoro','Kihingo'),
	(32,'Nakuru','Njoro','Nessuit'),
	(32,'Nakuru','Njoro','Lare'),
	(32,'Nakuru','Njoro','Njoro'),
	(32,'Nakuru','Molo','Mariashoni'),
	(32,'Nakuru','Molo','Elburgon'),
	(32,'Nakuru','Molo','Turi'),
	(32,'Nakuru','Molo','Molo'),
	(32,'Nakuru','Gilgil','Gilgil'),
	(32,'Nakuru','Gilgil','Elementaita'),
	(32,'Nakuru','Gilgil','Mbaruk/Eburu'),
	(32,'Nakuru','Gilgil','Malewa West'),
	(32,'Nakuru','Gilgil','Murindati'),
	(32,'Nakuru','Naivasha','Biashara'),
	(32,'Nakuru','Naivasha','Hells Gate'),
	(32,'Nakuru','Naivasha','Lake View'),
	(32,'Nakuru','Naivasha','Maiella'),
	(32,'Nakuru','Naivasha','Mai Mahiu'),
	(32,'Nakuru','Naivasha','Olkaria'),
	(32,'Nakuru','Naivasha','Naivasha East'),
	(32,'Nakuru','Naivasha','Viwandani'),
	(32,'Nakuru','Kuresoi North','Kiptororo'),
	(32,'Nakuru','Kuresoi North','Nyota'),
	(32,'Nakuru','Kuresoi North','Sirikwa'),
	(32,'Nakuru','Kuresoi North','Kamara'),
	(32,'Nakuru','Kuresoi South','Amalo'),
	(32,'Nakuru','Kuresoi South','Keringet'),
	(32,'Nakuru','Kuresoi South','Kiptagich'),
	(32,'Nakuru','Kuresoi South','Tinet'),
	(32,'Nakuru','Bahati','Dundori'),
	(32,'Nakuru','Bahati','Kabatini'),
	(32,'Nakuru','Bahati','Kiamaina'),
	(32,'Nakuru','Bahati','Lanet/Umoja'),
	(32,'Nakuru','Bahati','Bahati'),
	(32,'Nakuru','Rongai','Menengai West'),
	(32,'Nakuru','Rongai','Soin'),
	(32,'Nakuru','Rongai','Visoi'),
	(32,'Nakuru','Rongai','Mosop'),
	(32,'Nakuru','Rongai','Solai'),
	(32,'Nakuru','Subukia','Subukia'),
	(32,'Nakuru','Subukia','Waseges'),
	(32,'Nakuru','Subukia','Kabazi'),
	(33,'Narok','Narok North','Olpusimoru'),
	(33,'Narok','Narok North','Olokurto'),
	(33,'Narok','Narok North','Narok Town'),
	(33,'Narok','Narok North','Nkareta''Olorropil'),
	(33,'Narok','Narok North','Melili'),
	(33,'Narok','Narok South','Majimoto/Naroos'),
	(33,'Narok','Narok South','Uraololulung’a'),
	(33,'Narok','Narok South','Melelo'),
	(33,'Narok','Narok South','Loita'),
	(33,'Narok','Narok South','Sogoo'),
	(33,'Narok','Narok South','Sagamian'),
	(33,'Narok','Narok East','Mosiro'),
	(33,'Narok','Narok East','Ildamat'),
	(33,'Narok','Narok East','Keekonyokie'),
	(33,'Narok','Narok East','Suswa'),
	(33,'Narok','Narok West','Ilmotiok'),
	(33,'Narok','Narok West','Mara'),
	(33,'Narok','Narok West','Siana'),
	(33,'Narok','Narok West','Naikarra'),
	(33,'Narok','Kilgoris','Kilgoris Central'),
	(33,'Narok','Kilgoris','Keyian'),
	(33,'Narok','Kilgoris','Angata Barikoi'),
	(33,'Narok','Kilgoris','Shankoe'),
	(33,'Narok','Kilgoris','Kimintet'),
	(33,'Narok','Kilgoris','Lolgorian'),
	(33,'Narok','Emurua Dikirr','Ilkerin'),
	(33,'Narok','Emurua Dikirr','Ololmasani'),
	(33,'Narok','Emurua Dikirr','Mogondo'),
	(33,'Narok','Emurua Dikirr','Kapsasian'),
	(34,'Kajiado','Kajiado Central','Purko'),
	(34,'Kajiado','Kajiado Central','Ildamat'),
	(34,'Kajiado','Kajiado Central','Dalalekutuk'),
	(34,'Kajiado','Kajiado Central','Matapato North'),
	(34,'Kajiado','Kajiado Central','Matapato South'),
	(34,'Kajiado','Kajiado East','Kaputiei North'),
	(34,'Kajiado','Kajiado East','Kitengela'),
	(34,'Kajiado','Kajiado East','Oloosirkon/Sholinke'),
	(34,'Kajiado','Kajiado East','Kenyawa-Poka'),
	(34,'Kajiado','Kajiado East','Imaroro'),
	(34,'Kajiado','Kajiado North','Olkeri'),
	(34,'Kajiado','Kajiado North','Ongata Rongai'),
	(34,'Kajiado','Kajiado North','Nkaimurunya'),
	(34,'Kajiado','Kajiado North','Oloolua'),
	(34,'Kajiado','Kajiado North','Ngong'),
	(34,'Kajiado','Kajiado West','  Keekonyokie'),
	(34,'Kajiado','Kajiado West','Iloodokilani'),
	(34,'Kajiado','Kajiado West','Magadi'),
	(34,'Kajiado','Kajiado West','Ewuaso Oonkidong’i'),
	(34,'Kajiado','Kajiado West','Mosiro'),
	(34,'Kajiado','Kajiado South','Entonet/Lenkisi'),
	(34,'Kajiado','Kajiado South','Mbirikani/Eselen'),
	(34,'Kajiado','Kajiado South','Keikuku'),
	(34,'Kajiado','Kajiado South','Rombo'),
	(34,'Kajiado','Kajiado South','Kimana'),
	(35,'Kericho','Ainamoi','Kapsoit'),
	(35,'Kericho','Ainamoi','Ainamoi'),
	(35,'Kericho','Ainamoi','Kipchebor'),
	(35,'Kericho','Ainamoi','Kapkugerwet'),
	(35,'Kericho','Ainamoi','Kipchimchim'),
	(35,'Kericho','Ainamoi','Kapsaos'),
	(35,'Kericho','Belgut','Waldai'),
	(35,'Kericho','Belgut','Kabianga'),
	(35,'Kericho','Belgut','Cheptororiet/Seretut'),
	(35,'Kericho','Belgut','Chaik'),
	(35,'Kericho','Belgut','Kapsuser'),
	(35,'Kericho','Bureti','Kisiara'),
	(35,'Kericho','Bureti','Tebesonik'),
	(35,'Kericho','Bureti','Cheboin'),
	(35,'Kericho','Bureti','Chemosot'),
	(35,'Kericho','Bureti','Litein'),
	(35,'Kericho','Bureti','Cheplanget'),
	(35,'Kericho','Bureti','Kapkatet'),
	(35,'Kericho','Kipkelion East','Londiani'),
	(35,'Kericho','Kipkelion East','Kedowa/Kimugul'),
	(35,'Kericho','Kipkelion East','Chepseon'),
	(35,'Kericho','Kipkelion East','Tendeno/Sorget'),
	(35,'Kericho','Kipkelion West','Kunyak'),
	(35,'Kericho','Kipkelion West','Kamasian'),
	(35,'Kericho','Kipkelion West','Kipkelion'),
	(35,'Kericho','Kipkelion West','Chilchila'),
	(35,'Kericho','Soin Sigowet','Sigowet'),
	(35,'Kericho','Soin Sigowet','Kaplelartet'),
	(35,'Kericho','Soin Sigowet','Soliat'),
	(35,'Kericho','Soin Sigowet','Soin'),
	(36,'Bomet','Sotik','Ndanai/Abosi'),
	(36,'Bomet','Sotik','Chemagel'),
	(36,'Bomet','Sotik','Kipsonoi'),
	(36,'Bomet','Sotik','Apletundo'),
	(36,'Bomet','Sotik','Rongena/Manare T'),
	(36,'Bomet','Bomet Central','Silibwet Township'),
	(36,'Bomet','Bomet Central','Ndaraweta'),
	(36,'Bomet','Bomet Central',' Singorwet'),
	(36,'Bomet','Bomet Central','Chesoen'),
	(36,'Bomet','Bomet Central','Mutarakwa'),
	(36,'Bomet','Bomet East','Merigi'),
	(36,'Bomet','Bomet East','Kembu'),
	(36,'Bomet','Bomet East','Longisa'),
	(36,'Bomet','Bomet East','Kipreres'),
	(36,'Bomet','Bomet East','Chemaner'),
	(36,'Bomet','Chepalungu','  Kong’asis'),
	(36,'Bomet','Chepalungu',' Nyangores'),
	(36,'Bomet','Chepalungu','Sigor'),
	(36,'Bomet','Chepalungu',' Chebunyo'),
	(36,'Bomet','Chepalungu','Siongiroi'),
	(36,'Bomet','Konoin','Chepchabas'),
	(36,'Bomet','Konoin','Kimulot'),
	(36,'Bomet','Konoin','Mogogosiek'),
	(36,'Bomet','Konoin','Boito'),
	(36,'Bomet','Konoin',' Embomos'),
	(37,'Kakamega','Butere','Marama West'),
	(37,'Kakamega','Butere','Marama Central'),
	(37,'Kakamega','Butere','Marenyo-Shianda'),
	(37,'Kakamega','Butere','Maram North'),
	(37,'Kakamega','Butere','Marama South'),
	(37,'Kakamega','Ikolomani','Idakho South'),
	(37,'Kakamega','Ikolomani','Idakho East'),
	(37,'Kakamega','Ikolomani','Idakho North'),
	(37,'Kakamega','Ikolomani','Idakho Central'),
	(37,'Kakamega','Khwisero','Kisa North'),
	(37,'Kakamega','Khwisero','Kisa East'),
	(37,'Kakamega','Khwisero','Kisa West'),
	(37,'Kakamega','Khwisero','Kisa Central'),
	(37,'Kakamega','Lurambi','Butsotso East'),
	(37,'Kakamega','Lurambi','Butsotso South'),
	(37,'Kakamega','Lurambi','Butsotso Central'),
	(37,'Kakamega','Lurambi','Sheywe'),
	(37,'Kakamega','Lurambi','Mahiakalo'),
	(37,'Kakamega','Lurambi','Shirere'),
	(37,'Kakamega','Likuyani','Likuyani'),
	(37,'Kakamega','Likuyani','Sango');
INSERT INTO county VALUES (37,'Kakamega','Likuyani','Kongoni'),
	(37,'Kakamega','Likuyani','Nzoia'),
	(37,'Kakamega','Likuyani','Sinoko'),
	(37,'Kakamega','Malava','West Kabras'),
	(37,'Kakamega','Malava','Chemuche East'),
	(37,'Kakamega','Malava','Kabras'),
	(37,'Kakamega','Malava','Butali/Chegulo'),
	(37,'Kakamega','Malava','Manda-Shivanga'),
	(37,'Kakamega','Malava','Shirugu-Mugai'),
	(37,'Kakamega','Malava','South Kabras'),
	(37,'Kakamega','Matungu','Koyonzo'),
	(37,'Kakamega','Matungu','Kholera'),
	(37,'Kakamega','Matungu','Khalaba'),
	(37,'Kakamega','Matungu','Mayoni'),
	(37,'Kakamega','Matungu','Namamali'),
	(37,'Kakamega','Mumias East','Lusheya/Lubinu'),
	(37,'Kakamega','Mumias East','Malaha/Isongo/Makunga'),
	(37,'Kakamega','Mumias East','East Wanga'),
	(37,'Kakamega','Mumias West','Mumias Central'),
	(37,'Kakamega','Mumias West','Mumias North'),
	(37,'Kakamega','Mumias West','Etenje'),
	(37,'Kakamega','Mumias West','Musanda'),
	(37,'Kakamega','Navakholo','Ingostse-Mathia'),
	(37,'Kakamega','Navakholo','Shinoyi-Shikomari'),
	(37,'Kakamega','Navakholo','Esumeyia'),
	(37,'Kakamega','Navakholo','Bunyala West'),
	(37,'Kakamega','Navakholo','Bunyal East'),
	(37,'Kakamega','Navakholo','Bunyala Central'),
	(37,'Kakamega','Lugari','Mautuma'),
	(37,'Kakamega','Lugari','Lugari'),
	(37,'Kakamega','Lugari','Lumakanda'),
	(37,'Kakamega','Lugari','Chekalini'),
	(37,'Kakamega','Lugari','Chevaywa'),
	(37,'Kakamega','Lugari','Lawandeti'),
	(37,'Kakamega','Shinyalu','Mautuma'),
	(37,'Kakamega','Shinyalu','Lugari'),
	(37,'Kakamega','Shinyalu','Lumakanda'),
	(37,'Kakamega','Shinyalu','Chekalini'),
	(37,'Kakamega','Shinyalu','Chevaywa'),
	(37,'Kakamega','Shinyalu','Lawandeti'),
	(38,'Vihiga','Emuhaya','North East Bunyore'),
	(38,'Vihiga','Emuhaya','Central Bunyore'),
	(38,'Vihiga','Emuhaya','West Bunyore'),
	(38,'Vihiga','Hamisi','Shiru'),
	(38,'Vihiga','Hamisi','Gisambai'),
	(38,'Vihiga','Hamisi','Shamakhokho'),
	(38,'Vihiga','Hamisi','Banja'),
	(38,'Vihiga','Hamisi','Muhudi'),
	(38,'Vihiga','Hamisi','Tambaa'),
	(38,'Vihiga','Hamisi','Jepkoyai'),
	(38,'Vihiga','Sabatia','Lyaduywa/Izava'),
	(38,'Vihiga','Sabatia','West Sabatia'),
	(38,'Vihiga','Sabatia','Chavakali'),
	(38,'Vihiga','Sabatia','North Maragoli'),
	(38,'Vihiga','Sabatia','Wodanga'),
	(38,'Vihiga','Sabatia','Busali'),
	(38,'Vihiga','Vihiga','Lugaga-Wamuluma'),
	(38,'Vihiga','Vihiga','South Maragoli'),
	(38,'Vihiga','Vihiga','Central Maragoli'),
	(38,'Vihiga','Vihiga','Mungoma'),
	(38,'Vihiga','Luanda','Luanda Township'),
	(38,'Vihiga','Luanda','Wemilabi'),
	(38,'Vihiga','Luanda','Mwibona'),
	(38,'Vihiga','Luanda','Luanda South'),
	(38,'Vihiga','Luanda','Emabungo'),
	(39,'Bungoma','Bumula','Bumula'),
	(39,'Bungoma','Bumula','Khasoko'),
	(39,'Bungoma','Bumula','Kabula'),
	(39,'Bungoma','Bumula','Kimaeti'),
	(39,'Bungoma','Bumula','South Bukusu'),
	(39,'Bungoma','Bumula','Siboti'),
	(39,'Bungoma','Kanduyi','Bukembe West'),
	(39,'Bungoma','Kanduyi','Bukembe East'),
	(39,'Bungoma','Kanduyi','Township'),
	(39,'Bungoma','Kanduyi','Khalaba'),
	(39,'Bungoma','Kanduyi','Musikoma'),
	(39,'Bungoma','Kanduyi','East Snag’alo'),
	(39,'Bungoma','Kanduyi','Marakatu'),
	(39,'Bungoma','Kanduyi','Tuuti'),
	(39,'Bungoma','Kanduyi','West Sang’alo'),
	(39,'Bungoma','Webuye East','Mihuu'),
	(39,'Bungoma','Webuye East','Ndivisi'),
	(39,'Bungoma','Webuye East','Maraka'),
	(39,'Bungoma','Webuye West','Sitikho'),
	(39,'Bungoma','Webuye West','Matulo'),
	(39,'Bungoma','Webuye West','Bokoli'),
	(39,'Bungoma','Mt. Elgon','Cheptais'),
	(39,'Bungoma','Mt. Elgon','Chesikaki'),
	(39,'Bungoma','Mt. Elgon','Chepyuk'),
	(39,'Bungoma','Mt. Elgon','Kapkateny'),
	(39,'Bungoma','Mt. Elgon','Kaptama'),
	(39,'Bungoma','Mt. Elgon','Elgon'),
	(39,'Bungoma','Sirisia','Namwela'),
	(39,'Bungoma','Sirisia','Malakisi/South Kulisiru'),
	(39,'Bungoma','Sirisia','Lwandanyi'),
	(39,'Bungoma','Tongaren','Mbakalo'),
	(39,'Bungoma','Tongaren','Naitiri/Kabuyefwe'),
	(39,'Bungoma','Tongaren','Milima'),
	(39,'Bungoma','Tongaren','Ndalu/Tabani'),
	(39,'Bungoma','Tongaren','Tongaren'),
	(39,'Bungoma','Tongaren','Soysambu/Mitua'),
	(39,'Bungoma','Kabuchai','Kabuchai/Chwele'),
	(39,'Bungoma','Kabuchai','West Nalondo'),
	(39,'Bungoma','Kabuchai','Bwake/Luuya'),
	(39,'Bungoma','Kabuchai','Mukuyuni'),
	(39,'Bungoma','Kabuchai','South Bukusu'),
	(39,'Bungoma','Kimilili','Kibingei'),
	(39,'Bungoma','Kimilili','Kimilili'),
	(39,'Bungoma','Kimilili','Maeni'),
	(39,'Bungoma','Kimilili','Kamukuywa'),
	(40,'Busia','Teso North','MALABA CENTRAL'),
	(40,'Busia','Teso North','MALABA NORTH'),
	(40,'Busia','Teso North','ANG’URAI SOUTH'),
	(40,'Busia','Teso North','MALABA SOUTH'),
	(40,'Busia','Teso North','ANG’URAI NORTH'),
	(40,'Busia','Teso North','ANG’URAI EAST'),
	(40,'Busia','Teso South','ANG''OROM'),
	(40,'Busia','Teso South','CHAKOI SOUTH'),
	(40,'Busia','Teso South','AMUKURA CENTRAL'),
	(40,'Busia','Teso South','CHAKOI NORTH'),
	(40,'Busia','Teso South','AMUKURA EAST'),
	(40,'Busia','Teso South','AMUKURA WEST'),
	(40,'Busia','Nambale','NAMBALE TOWNSHIP'),
	(40,'Busia','Nambale','BUKHAYO NORTH/WALTSI'),
	(40,'Busia','Nambale','BUKHAYO EAST'),
	(40,'Busia','Nambale','BUKHAYO CENTRAL'),
	(40,'Busia','Matayos','BUKHAYO WEST'),
	(40,'Busia','Matayos','MAYENJE'),
	(40,'Busia','Matayos','MATAYOS SOUTHBUSIBWABO'),
	(40,'Busia','Matayos','BURUMBA'),
	(40,'Busia','Butula','MARACHI WESTKINGANDOLE'),
	(40,'Busia','Butula','MARACHI CENTRAL'),
	(40,'Busia','Butula','MARACHI EAST'),
	(40,'Busia','Butula','MARACHI NORTH'),
	(40,'Busia','Butula','ELUGULU'),
	(40,'Busia','Funyula','NAMBOBOTO NAMBUKU'),
	(40,'Busia','Funyula','NANGINA'),
	(40,'Busia','Funyula','AGENG''A NANGUBA'),
	(40,'Busia','Funyula','BWIRI'),
	(41,'Siaya','Alego Usonga','Usonga'),
	(41,'Siaya','Alego Usonga','West Alego'),
	(41,'Siaya','Alego Usonga','Central Alego'),
	(41,'Siaya','Alego Usonga','Siaya Township'),
	(41,'Siaya','Alego Usonga','North Alego'),
	(41,'Siaya','Alego Usonga','South East Alego'),
	(41,'Siaya','Gem','North Gem'),
	(41,'Siaya','Gem','West Gem'),
	(41,'Siaya','Gem','Central Gem'),
	(41,'Siaya','Gem','Yala Township'),
	(41,'Siaya','Gem','East Gem'),
	(41,'Siaya','Gem','South Gem'),
	(41,'Siaya','Bondo','West Yimbo'),
	(41,'Siaya','Bondo','Central Sakwa'),
	(41,'Siaya','Bondo','South Sakwa'),
	(41,'Siaya','Bondo','Yimbo East'),
	(41,'Siaya','Bondo','West Sakwa'),
	(41,'Siaya','Bondo','North Sakwa'),
	(41,'Siaya','Rarieda','Gem Rae'),
	(41,'Siaya','Rarieda','East Asembo'),
	(41,'Siaya','Rarieda','West Asembo'),
	(41,'Siaya','Rarieda','Central Asembo'),
	(41,'Siaya','Rarieda','South West Asembo'),
	(41,'Siaya','Rarieda','North West Asembo'),
	(41,'Siaya','Rarieda','North East Asembo'),
	(41,'Siaya','Rarieda','South East Asembo'),
	(41,'Siaya','Rarieda','Nyang''oma Kogelo'),
	(41,'Siaya','Rarieda','West Uyoma'),
	(41,'Siaya','Rarieda','Central Uyoma'),
	(41,'Siaya','Rarieda','North Uyoma'),
	(41,'Siaya','Ugenya','East Asembo'),
	(41,'Siaya','Ugenya','West Asembo'),
	(41,'Siaya','Ugenya','North Uyoma'),
	(41,'Siaya','Ugenya','South Uyoma'),
	(41,'Siaya','Ugenya','West Uyoma'),
	(41,'Siaya','Ugunja','Sidindi'),
	(41,'Siaya','Ugunja','Sigomere'),
	(41,'Siaya','Ugunja','Ugunja'),
	(42,'Kisumu','Kisumu Central','Railways'),
	(42,'Kisumu','Kisumu Central','Migosi'),
	(42,'Kisumu','Kisumu Central','Shaurimoyo Kaloleni'),
	(42,'Kisumu','Kisumu Central','Market Milimani'),
	(42,'Kisumu','Kisumu Central','Kondele'),
	(42,'Kisumu','Kisumu Central','Nyalenda B'),
	(42,'Kisumu','Kisumu East','Kajulu'),
	(42,'Kisumu','Kisumu East','Kolwa East'),
	(42,'Kisumu','Kisumu East','Manyatta ''B'''),
	(42,'Kisumu','Kisumu East','Nyalenda ''A'''),
	(42,'Kisumu','Kisumu East','Kolwa Central'),
	(42,'Kisumu','Kisumu West','South West Kisumu'),
	(42,'Kisumu','Kisumu West','Cetral Kisumu'),
	(42,'Kisumu','Kisumu West','Kisumu North'),
	(42,'Kisumu','Kisumu West','West Kisumu'),
	(42,'Kisumu','Kisumu West','North West Kisumu'),
	(42,'Kisumu','Seme','West Seme'),
	(42,'Kisumu','Seme','Central Seme'),
	(42,'Kisumu','Seme','East Seme'),
	(42,'Kisumu','Seme','North Seme'),
	(42,'Kisumu','Nyando','East Kano/Waidhi'),
	(42,'Kisumu','Nyando','Awasi/Onjiko'),
	(42,'Kisumu','Nyando','Ahero'),
	(42,'Kisumu','Nyando','Kabonyo/Kanyag Wal'),
	(42,'Kisumu','Nyando','Kobura'),
	(42,'Kisumu','Muhoroni','Miwani'),
	(42,'Kisumu','Muhoroni','Ombeyi'),
	(42,'Kisumu','Muhoroni','Masogo/Nyag’oma'),
	(42,'Kisumu','Muhoroni','Chemeli/Muhoroni/Koru'),
	(42,'Kisumu','Nyakach','South East Nyakach'),
	(42,'Kisumu','Nyakach','West Nyakach'),
	(42,'Kisumu','Nyakach','North Nyakach'),
	(42,'Kisumu','Nyakach','Central Nyakach'),
	(42,'Kisumu','Nyakach','South West Nyakach'),
	(43,'Homa Bay','Homa Bay Town','Homa Bay Central'),
	(43,'Homa Bay','Homa Bay Town','Homa Bay Arujo'),
	(43,'Homa Bay','Homa Bay Town','Homa Bay West'),
	(43,'Homa Bay','Homa Bay Town','Homa Bay East'),
	(43,'Homa Bay','Kabondo Kasipul','Kabondo East'),
	(43,'Homa Bay','Kabondo Kasipul','Kabondo West'),
	(43,'Homa Bay','Kabondo Kasipul','Kokwanyo'),
	(43,'Homa Bay','Kabondo Kasipul','Kakelo-Kojwach'),
	(43,'Homa Bay','Karachuonyo','West Karachuonyo'),
	(43,'Homa Bay','Karachuonyo','North Karachuonyo'),
	(43,'Homa Bay','Karachuonyo','Central Kanyaluo'),
	(43,'Homa Bay','Karachuonyo','Kibiri'),
	(43,'Homa Bay','Karachuonyo','Wangchieng'),
	(43,'Homa Bay','Karachuonyo','Kendu Bay Town'),
	(43,'Homa Bay','Kasipul','West Kasipul'),
	(43,'Homa Bay','Kasipul','South Kasipul'),
	(43,'Homa Bay','Kasipul','Central Kasipul'),
	(43,'Homa Bay','Kasipul','East Kamagak'),
	(43,'Homa Bay','Kasipul','West Kamagak'),
	(43,'Homa Bay','Ndhiwa','Kwabwai'),
	(43,'Homa Bay','Ndhiwa','Kanyadoto'),
	(43,'Homa Bay','Ndhiwa','Kanyikela'),
	(43,'Homa Bay','Ndhiwa','Kabuoch North'),
	(43,'Homa Bay','Ndhiwa','Kabuoch South/Pala'),
	(43,'Homa Bay','Ndhiwa','Kanyamwa Kologi'),
	(43,'Homa Bay','Ndhiwa','Kanyamwa Kosewe'),
	(43,'Homa Bay','Rangwe','West Gem'),
	(43,'Homa Bay','Rangwe','East Gem'),
	(43,'Homa Bay','Rangwe','Kagan'),
	(43,'Homa Bay','Rangwe','Kochia'),
	(43,'Homa Bay','Suba North','Mfangano Island'),
	(43,'Homa Bay','Suba North','Rusinga Island'),
	(43,'Homa Bay','Suba North','Kasgunga'),
	(43,'Homa Bay','Suba North','Gember'),
	(43,'Homa Bay','Suba North','Lambwe'),
	(43,'Homa Bay','Suba South','Gwassi South'),
	(43,'Homa Bay','Suba South','Gwassi North'),
	(43,'Homa Bay','Suba South','Kaksingri West'),
	(43,'Homa Bay','Suba South','Ruma-Kakshingri');
INSERT INTO county VALUES (44,'Migori','Rongo','North Kamagambo'),
	(44,'Migori','Rongo','Central Kamagambo'),
	(44,'Migori','Rongo','East Kamagambo'),
	(44,'Migori','Rongo','South Kamagambo'),
	(44,'Migori','Awendo','North East Sakwa'),
	(44,'Migori','Awendo','South Sakwa'),
	(44,'Migori','Awendo','West Sakwa'),
	(44,'Migori','Awendo','Central Sakwa'),
	(44,'Migori','Suna East','God Jope'),
	(44,'Migori','Suna East','Suna Central'),
	(44,'Migori','Suna East','Kakrao'),
	(44,'Migori','Suna East','Kwa'),
	(44,'Migori','Suna West','Wiga'),
	(44,'Migori','Suna West','Wasweta II'),
	(44,'Migori','Suna West','Ragan-Oruba'),
	(44,'Migori','Suna West','Wasimbete'),
	(44,'Migori','Uriri','West Kanyamkago'),
	(44,'Migori','Uriri','North Kanyamkago'),
	(44,'Migori','Uriri','Central Kanyam Kago'),
	(44,'Migori','Uriri','South Kanyamkago'),
	(44,'Migori','Uriri','East Kanyamkago'),
	(44,'Migori','Nyatike','Kachien’g'),
	(44,'Migori','Nyatike','Kanyasa'),
	(44,'Migori','Nyatike','North Kadem'),
	(44,'Migori','Nyatike','Macalder/ Kanyarwanda'),
	(44,'Migori','Nyatike','Kaler'),
	(44,'Migori','Nyatike','Got Kachola'),
	(44,'Migori','Nyatike','Muhuru'),
	(44,'Migori','Kuria East','Gokeharaka/Getamwega'),
	(44,'Migori','Kuria East','Ntimaru West'),
	(44,'Migori','Kuria East','Ntimaru East'),
	(44,'Migori','Kuria East','Nyabasi East'),
	(44,'Migori','Kuria East','Nyabasi West'),
	(44,'Migori','Kuria West','Bukira East'),
	(44,'Migori','Kuria West','Bukira Central/ Ikerege'),
	(44,'Migori','Kuria West','Isibania'),
	(44,'Migori','Kuria West','Makerero'),
	(44,'Migori','Kuria West','Masaba'),
	(44,'Migori','Kuria West','Tagare'),
	(44,'Migori','Kuria West','Nyamosense/Ko Mosoko'),
	(45,'Kisii','Kitutu Chache North','MONYERERO'),
	(45,'Kisii','Kitutu Chache North','SENSI'),
	(45,'Kisii','Kitutu Chache North','MARANI'),
	(45,'Kisii','Kitutu Chache North','MWAMONARI'),
	(45,'Kisii','Kitutu Chache South','BOGUSERO'),
	(45,'Kisii','Kitutu Chache South','BOGEKA'),
	(45,'Kisii','Kitutu Chache South','NYAKOE'),
	(45,'Kisii','Kitutu Chache South','KITUTU CENTRAL'),
	(45,'Kisii','Kitutu Chache South','NYATIEKO'),
	(45,'Kisii','Nyaribari Masaba','ICHUNI'),
	(45,'Kisii','Nyaribari Masaba','NYAMASIBI'),
	(45,'Kisii','Nyaribari Masaba','MASIMBA'),
	(45,'Kisii','Nyaribari Masaba','GESUSU'),
	(45,'Kisii','Nyaribari Masaba','KIAMOKAMA'),
	(45,'Kisii','Nyaribari Chache','BOBARACHO'),
	(45,'Kisii','Nyaribari Chache','KISII CENTRAL'),
	(45,'Kisii','Nyaribari Chache','KEUMBU'),
	(45,'Kisii','Nyaribari Chache','KIOGORO'),
	(45,'Kisii','Nyaribari Chache','BIRONGO'),
	(45,'Kisii','Nyaribari Chache','IBENO'),
	(45,'Kisii','Bomachoge Borabu','BORABU MASABA'),
	(45,'Kisii','Bomachoge Borabu','BOOCHI BORABU'),
	(45,'Kisii','Bomachoge Borabu','BOKIMONGE'),
	(45,'Kisii','Bomachoge Borabu','MAGENCHE'),
	(45,'Kisii','Bomachoge Chache','MAJOGE BASI'),
	(45,'Kisii','Bomachoge Chache','BOOCHI/TENDERE'),
	(45,'Kisii','Bomachoge Chache','BOSOTI/SENGERA'),
	(45,'Kisii','Bobasi','MASIGE WEST'),
	(45,'Kisii','Bobasi','MASIG EAST'),
	(45,'Kisii','Bobasi','BASI CENTRAL'),
	(45,'Kisii','Bobasi','NYACHEKI'),
	(45,'Kisii','Bobasi','BASSI BOGETAORIO'),
	(45,'Kisii','Bobasi','BOBASI CHACHE'),
	(45,'Kisii','Bobasi','SAMETA/ MOKWERERO'),
	(45,'Kisii','Bobasi','BOBASI/ BOITANGARE'),
	(45,'Kisii','South Mugirango','BOGETENGA'),
	(45,'Kisii','South Mugirango','BORABU/CHITAGO'),
	(45,'Kisii','South Mugirango','MOTICHO'),
	(45,'Kisii','South Mugirango','GETENGA'),
	(45,'Kisii','South Mugirango','TABAKA'),
	(45,'Kisii','South Mugirango','BOIKANGA'),
	(45,'Kisii','Bonchari','BOMARIBA'),
	(45,'Kisii','Bonchari','BOGIAKUMU'),
	(45,'Kisii','Bonchari','BOKEIRA'),
	(45,'Kisii','Bonchari','RIANA'),
	(46,'Nyamira','Borabu','Mekenene'),
	(46,'Nyamira','Borabu','Kiabonyoru'),
	(46,'Nyamira','Borabu','Esise'),
	(46,'Nyamira','Borabu','Nyansiongo'),
	(46,'Nyamira','Kitutu Masaba','Rigoma'),
	(46,'Nyamira','Kitutu Masaba','Gachuba'),
	(46,'Nyamira','Kitutu Masaba','Kemera'),
	(46,'Nyamira','Kitutu Masaba','Magombo'),
	(46,'Nyamira','Kitutu Masaba','Manga'),
	(46,'Nyamira','Kitutu Masaba','Gesima'),
	(46,'Nyamira','West Mugirango','Nyamaiya'),
	(46,'Nyamira','West Mugirango','Bogichora'),
	(46,'Nyamira','West Mugirango','Bosamaro'),
	(46,'Nyamira','West Mugirango','Bonyamatuta'),
	(46,'Nyamira','West Mugirango','Township'),
	(46,'Nyamira','North Mugirango','Itibo'),
	(46,'Nyamira','North Mugirango','Bomwagamo'),
	(46,'Nyamira','North Mugirango','Bokeira'),
	(46,'Nyamira','North Mugirango','Magwagwa'),
	(46,'Nyamira','North Mugirango','Ekerenyo'),
	(47,'Nairobi','Westlands','Kitisuru'),
	(47,'Nairobi','Westlands','Parklands/Highridge'),
	(47,'Nairobi','Westlands','Karura'),
	(47,'Nairobi','Westlands','Kangemi'),
	(47,'Nairobi','Westlands','Mountain View'),
	(47,'Nairobi','Dagoretti North','Kilimani'),
	(47,'Nairobi','Dagoretti North','Kawangware'),
	(47,'Nairobi','Dagoretti North','Gatina'),
	(47,'Nairobi','Dagoretti North','Kileleshwa'),
	(47,'Nairobi','Dagoretti North','Kabiro'),
	(47,'Nairobi','Dagoretti South','Mutu-Ini'),
	(47,'Nairobi','Dagoretti South','Ngando'),
	(47,'Nairobi','Dagoretti South','Riruta'),
	(47,'Nairobi','Dagoretti South','Uthiru/Ruthimitu'),
	(47,'Nairobi','Dagoretti South','Waithaka'),
	(47,'Nairobi','Lang''ata','Karen'),
	(47,'Nairobi','Lang''ata','Nairobi West'),
	(47,'Nairobi','Lang''ata','Mugumu-Ini'),
	(47,'Nairobi','Lang''ata','South C'),
	(47,'Nairobi','Lang''ata','Nyayo Highrise'),
	(47,'Nairobi','Kibra','Woodley/Kenyatta Golf Course'),
	(47,'Nairobi','Kibra','Sarang''ombe'),
	(47,'Nairobi','Kibra','Makina'),
	(47,'Nairobi','Kibra','Lindi'),
	(47,'Nairobi','Kibra','Laini Saba'),
	(47,'Nairobi','Roysambu','Kahawa West'),
	(47,'Nairobi','Roysambu','Roysambu'),
	(47,'Nairobi','Roysambu','Githurai'),
	(47,'Nairobi','Roysambu','Kahawa'),
	(47,'Nairobi','Roysambu','Zimmerman'),
	(47,'Nairobi','Kasarani','Kasarani'),
	(47,'Nairobi','Kasarani','Njiru'),
	(47,'Nairobi','Kasarani','Clay City'),
	(47,'Nairobi','Kasarani','Mwiki'),
	(47,'Nairobi','Kasarani','Ruai'),
	(47,'Nairobi','Ruaraka','Utalii'),
	(47,'Nairobi','Ruaraka','Korogocho'),
	(47,'Nairobi','Ruaraka','Lucky Summer'),
	(47,'Nairobi','Ruaraka','Mathare North'),
	(47,'Nairobi','Ruaraka','Baba Dogo'),
	(47,'Nairobi','Embakasi South','Kwa Njenga'),
	(47,'Nairobi','Embakasi South','Imara Daima'),
	(47,'Nairobi','Embakasi South','Kware'),
	(47,'Nairobi','Embakasi South','Kwa Reuben'),
	(47,'Nairobi','Embakasi South','Pipeline'),
	(47,'Nairobi','Embakasi South','Embakasi North','Dandora Area I'),
	(47,'Nairobi','Embakasi South','Embakasi North','Dandora Area II'),
	(47,'Nairobi','Embakasi South','Embakasi North','Dandora Area III'),
	(47,'Nairobi','Embakasi South','Embakasi North','Dandora Area IV'),
	(47,'Nairobi','Embakasi South','Embakasi North','Kariobangi North'),
	(47,'Nairobi','Embakasi South','Embakasi Central','Kayole North'),
	(47,'Nairobi','Embakasi South','Embakasi Central','Kayole Central'),
	(47,'Nairobi','Embakasi South','Embakasi Central','Kariobangi South'),
	(47,'Nairobi','Embakasi South','Embakasi Central','Komarock'),
	(47,'Nairobi','Embakasi South','Embakasi Central','Matopeni / Spring Valley'),
	(47,'Nairobi','Embakasi South','Embakasi East','Utawala'),
	(47,'Nairobi','Embakasi South','Embakasi East','Upper Savanna'),
	(47,'Nairobi','Embakasi South','Embakasi East','Lower Savanna'),
	(47,'Nairobi','Embakasi South','Embakasi East','Embakasi'),
	(47,'Nairobi','Embakasi South','Embakasi East','Mihango'),
	(47,'Nairobi','Embakasi South','Embakasi West','Umoja 1'),
	(47,'Nairobi','Embakasi South','Embakasi West','Umoja 2'),
	(47,'Nairobi','Embakasi South','Embakasi West','Mowlem '),
	(47,'Nairobi','Embakasi South','Embakasi West','Kariobangi south'),
	(47,'Nairobi','Embakasi South','Embakasi West','Maringo/ Hamza'),
	(47,'Nairobi','Embakasi South','Makadara','Viwandani'),
	(47,'Nairobi','Embakasi South','Makadara','Harambee'),
	(47,'Nairobi','Embakasi South','Makadara','Makongeni'),
	(47,'Nairobi','Embakasi South','Makadara','Pumwani'),
	(47,'Nairobi','Embakasi South','Makadara','Eastleigh North'),
	(47,'Nairobi','Embakasi South','Kamukunji','Eastleigh South'),
	(47,'Nairobi','Embakasi South','Kamukunji','Nairobi Central'),
	(47,'Nairobi','Embakasi South','Kamukunji','Airbase'),
	(47,'Nairobi','Embakasi South','Kamukunji','California'),
	(47,'Nairobi','Embakasi South','Kamukunji','Mgara'),
	(47,'Nairobi','Embakasi South','Starehe','Nairobi South'),
	(47,'Nairobi','Embakasi South','Starehe','Hospital'),
	(47,'Nairobi','Embakasi South','Starehe','Ngara'),
	(47,'Nairobi','Embakasi South','Starehe','Pangani'),
	(47,'Nairobi','Embakasi South','Starehe','Landimawe'),
	(47,'Nairobi','Embakasi South','Starehe','Ziwani / Kariokor'),
	(47,'Nairobi','Embakasi South','Mathare','Mlango Kubwa'),
	(47,'Nairobi','Embakasi South','Mathare','Kiamaiko'),
	(47,'Nairobi','Embakasi South','Mathare','Ngei'),
	(47,'Nairobi','Embakasi South','Mathare','Huruma'),
	(47,'Nairobi','Embakasi South','Mathare','Mabatini');
